// BUILD-002 WP7 — FULL-CHAIN migration reproducibility + rollback proof (010–160).
//
// Extends apply-teardown.test.mjs from 010–050 to the WHOLE cockpit migration set. Connects to a
// throwaway local Postgres (PGPORT from run-migration-test-full.sh), builds the minimal asdair stub,
// applies EVERY migration in numeric order, re-applies for idempotency, asserts the BUILD-002 tables
// exist, tears down, and asserts the cockpit schema + roles are gone while the asdair stub is untouched.
// Never touches hosted MyPKA.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import pg from 'file:///C:/Fusion247PKA/services/control-plane/node_modules/pg/lib/index.js';

const MIG = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const PORT = Number(process.env.PGPORT || 0);
if (!PORT) { console.error('set PGPORT (run via run-migration-test-full.sh)'); process.exit(2); }
const readMig = (f) => fs.readFileSync(path.join(MIG, f), 'utf8');
const conn = (user) => new pg.Client({ host: '127.0.0.1', port: PORT, user, database: 'postgres' });

// Every numbered migration file, in numeric order (010…160). Excludes teardown.sql + seed/test dirs.
const files = fs.readdirSync(MIG)
  .filter((f) => /^\d{3}_.*\.sql$/.test(f))
  .sort((a, b) => Number(a.slice(0, 3)) - Number(b.slice(0, 3)));

let pass = 0, fail = 0;
const ok = (c, m) => { c ? (pass++, console.log('  PASS', m)) : (fail++, console.log('  FAIL', m)); };
const admin = conn('postgres');

async function main() {
  await admin.connect();
  // Minimal asdair stub (test scaffolding; the real schema pre-exists on hosted MyPKA).
  await admin.query(`create schema asdair`);
  await admin.query(`create table asdair.households (id bigint generated by default as identity primary key, name text unique not null, display_name text, notes text, created_at timestamptz default now())`);
  await admin.query(`create table asdair.regulars (id bigint generated by default as identity primary key, household_id bigint not null references asdair.households(id), name text not null, category text, source text default 'regular', typical_qty int, active boolean default true, created_at timestamptz default now(), updated_at timestamptz default now())`);
  await admin.query(`create table asdair.shopping_lists (id bigint generated by default as identity primary key, household_id bigint not null references asdair.households(id), list_date date not null, status text default 'pending', created_at timestamptz default now())`);
  await admin.query(`create table asdair.shopping_list_items (id bigint generated by default as identity primary key, list_id bigint not null references asdair.shopping_lists(id), item_name text, requested_qty int default 1, status text default 'requested', created_at timestamptz default now())`);
  console.log(`[full] asdair stub built; applying ${files.length} migrations: ${files.map((f) => f.slice(0, 3)).join(' ')}\n`);

  console.log('1) apply the full chain 010–160 (then re-apply for idempotency):');
  for (const f of files) { await admin.query(readMig(f)); console.log('   applied', f); }
  for (const f of files) await admin.query(readMig(f));
  ok(true, 'full migration chain applies AND re-applies cleanly (idempotent)');

  console.log('2) the BUILD-002 objects exist:');
  for (const t of ['cockpit.build', 'cockpit.build_contract', 'cockpit.youtube_source', 'cockpit.learning_candidate',
    'cockpit.learning_command', 'cockpit.decision_card', 'cockpit.follow_on_task', 'cockpit.decision_response', 'cockpit.command_request']) {
    ok((await admin.query(`select to_regclass($1) is not null e`, [t])).rows[0].e, `${t} exists`);
  }
  ok((await admin.query(`select count(*)::int n from pg_roles where rolname in ('cp_directus','cp_worker')`)).rows[0].n === 2, 'both cockpit roles exist');

  console.log('3) teardown reverses the entire cockpit layer:');
  await admin.query(readMig('teardown.sql'));
  ok((await admin.query(`select 1 from pg_namespace where nspname='cockpit'`)).rowCount === 0, 'cockpit schema fully removed');
  ok((await admin.query(`select to_regclass('cockpit.decision_response') is null g`)).rows[0].g, 'WP4 tables gone with the schema cascade');
  ok((await admin.query(`select count(*)::int n from pg_roles where rolname in ('cp_directus','cp_worker')`)).rows[0].n === 0, 'both roles removed');
  ok((await admin.query(`select to_regclass('asdair.regulars') is not null e`)).rows[0].e, 'asdair stub UNTOUCHED (teardown only removed the cockpit layer)');
  await admin.query(readMig('teardown.sql'));
  ok(true, 'teardown re-runs cleanly (idempotent)');

  console.log(`\nRESULT: ${fail === 0 ? 'PASS ✓' : 'FAIL ✗'} — ${pass} passed, ${fail} failed`);
}
main().catch((e) => { console.error('[full] error', e.message); fail++; }).finally(async () => { await admin.end().catch(() => {}); process.exit(fail === 0 ? 0 : 1); });
