// MyPKA cockpit migrations — reproducibility + rollback proof (connect-only).
//
// Connects to a throwaway local Postgres already started by run-migration-test.sh (PGPORT env),
// builds a MINIMAL asdair stub (test scaffolding — NOT Warwick's real schema, NOT hosted),
// applies migrations 010–040, proves the least-privilege seam reproduced, applies teardown.sql,
// and asserts every cockpit object is gone. Never touches hosted MyPKA. Cluster lifecycle is the
// bash driver's job (node-spawned initdb stalls under this machine's file scanning).
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import pg from 'file:///C:/Fusion247PKA/services/control-plane/node_modules/pg/lib/index.js';

const MIG = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const PORT = Number(process.env.PGPORT || 0);
if (!PORT) { console.error('set PGPORT (run via run-migration-test.sh)'); process.exit(2); }
const readMig = (f) => fs.readFileSync(path.join(MIG, f), 'utf8');
const conn = (user) => new pg.Client({ host: '127.0.0.1', port: PORT, user, database: 'postgres' });

let pass = 0, fail = 0;
const ok = (c, m) => { c ? (pass++, console.log('  PASS', m)) : (fail++, console.log('  FAIL', m)); };
async function expectErr(fn, code, m) { try { await fn(); fail++; console.log('  FAIL', m, '(no error)'); } catch (e) { (!code || e.code === code) ? (pass++, console.log('  PASS', m, `(${e.code})`)) : (fail++, console.log('  FAIL', m, `got ${e.code} want ${code}`)); } }

const admin = conn('postgres');
async function main() {
  await admin.connect();

  // ---- Minimal asdair stub (test scaffolding; the real schema pre-exists on hosted MyPKA) ----
  await admin.query(`create schema asdair`);
  await admin.query(`create table asdair.households (id bigint generated by default as identity primary key, name text unique not null, display_name text, notes text, created_at timestamptz default now())`);
  await admin.query(`create table asdair.regulars (id bigint generated by default as identity primary key, household_id bigint not null references asdair.households(id), name text not null, category text, source text default 'regular', typical_qty int, active boolean default true, created_at timestamptz default now(), updated_at timestamptz default now())`);
  await admin.query(`create table asdair.shopping_lists (id bigint generated by default as identity primary key, household_id bigint not null references asdair.households(id), list_date date not null, status text default 'pending', created_at timestamptz default now())`);
  await admin.query(`create table asdair.shopping_list_items (id bigint generated by default as identity primary key, list_id bigint not null references asdair.shopping_lists(id), item_name text, requested_qty int default 1, status text default 'requested', created_at timestamptz default now())`);
  console.log('[test] asdair stub built\n');

  console.log('1) apply migrations 010–040 (then re-apply for idempotency):');
  const files = ['010_directus_sys_schema.sql', '020_cockpit_roles.sql', '030_command_request.sql', '040_cockpit_grants.sql'];
  for (const f of files) { await admin.query(readMig(f)); console.log('   applied', f); }
  for (const f of files) await admin.query(readMig(f));
  ok(true, 'migrations apply AND re-apply cleanly (idempotent)');

  ok((await admin.query(`select 1 from pg_namespace where nspname='directus_sys'`)).rowCount === 1, 'directus_sys schema exists');
  ok((await admin.query(`select count(*)::int n from pg_roles where rolname in ('cp_directus','cp_worker')`)).rows[0].n === 2, 'both roles exist');
  ok((await admin.query(`select to_regclass('asdair.command_request') is not null as e`)).rows[0].e, 'command_request table exists');

  console.log('2) least-privilege boundary reproduced:');
  const hh = (await admin.query(`insert into asdair.households (name) values ('__stub__') returning id`)).rows[0].id;
  const reg = (await admin.query(`insert into asdair.regulars (household_id, name) values ($1,'Stub Milk') returning id`, [hh])).rows[0].id;
  const cockpit = conn('cp_directus'); await cockpit.connect();
  const worker = conn('cp_worker'); await worker.connect();
  await cockpit.query(`insert into asdair.command_request (requested_by, command, args, idempotency_key) values ('t','add_regular_to_next_week', $1::jsonb, 't-1')`, [JSON.stringify({ regular_id: reg, qty: 2 })]);
  ok(true, 'cp_directus can INSERT an intent');
  await expectErr(() => cockpit.query(`update asdair.command_request set status='done' where idempotency_key='t-1'`), '42501', 'cp_directus CANNOT update the queue');
  await expectErr(() => cockpit.query(`insert into asdair.shopping_list_items (list_id,item_name,requested_qty) values (1,'x',1)`), '42501', 'cp_directus CANNOT write shopping items');
  await expectErr(() => worker.query(`insert into asdair.command_request (requested_by,command,args,idempotency_key) values ('w','x','{}'::jsonb,'w-1')`), '42501', 'cp_worker CANNOT fabricate an intent');
  const list = (await worker.query(`insert into asdair.shopping_lists (household_id,status,list_date) values ($1,'next_week_draft',current_date+7) returning id`, [hh])).rows[0].id;
  await worker.query(`insert into asdair.shopping_list_items (list_id,item_name,requested_qty) values ($1,'Stub Milk',2)`, [list]);
  await worker.query(`update asdair.command_request set status='claimed', claimed_at=now() where idempotency_key='t-1'`);
  await worker.query(`update asdair.command_request set status='done', completed_at=now(), receipt='{"ok":true}'::jsonb where idempotency_key='t-1'`);
  ok(true, 'cp_worker can execute the effect + receipt the queue');
  await expectErr(() => admin.query(`insert into asdair.command_request (requested_by,command,args,idempotency_key,status) values ('a','x','{}'::jsonb,'g-1','claimed')`), '23514', 'insert-guard rejects status!=requested');
  await cockpit.end(); await worker.end();

  console.log('3) teardown reverses everything:');
  await admin.query(readMig('teardown.sql'));
  ok((await admin.query(`select 1 from pg_namespace where nspname='directus_sys'`)).rowCount === 0, 'directus_sys schema removed');
  ok((await admin.query(`select to_regclass('asdair.command_request') is null as g`)).rows[0].g, 'command_request removed');
  ok((await admin.query(`select count(*)::int n from pg_roles where rolname in ('cp_directus','cp_worker')`)).rows[0].n === 0, 'both roles removed');
  ok((await admin.query(`select to_regclass('asdair.regulars') is not null as e`)).rows[0].e, 'asdair stub tables UNTOUCHED (teardown only removed the cockpit layer)');
  await admin.query(readMig('teardown.sql'));
  ok(true, 'teardown re-runs cleanly (idempotent)');

  console.log(`\nRESULT: ${fail === 0 ? 'PASS ✓' : 'FAIL ✗'} — ${pass} passed, ${fail} failed`);
}
main().catch((e) => { console.error('[test] error', e.message); fail++; }).finally(async () => { await admin.end().catch(()=>{}); process.exit(fail === 0 ? 0 : 1); });
