// BUILD-002 WP5 — add_list_item handler proof against a THROWAWAY Postgres with the real asdair schema.
//   (run via run-add-list-item-test.sh — it provisions the cluster + sets PGPORT)
// Proves the Shopper write handler on synthetic data: insert, idempotency, correction, ambiguous
// (needs_decision), validation, allowlist, regression (add_regular still works), and no checkout/order
// side effect. NEVER touches Warwick's live household DB — only the final real write is Warwick-gated.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import pg from 'pg';
import { execute } from './asdairCommands.mjs';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const SCHEMA = path.resolve(HERE, '..', '..', 'asdair', 'db', '001_asdair_schema.sql');
const PORT = Number(process.env.PGPORT || 0);
if (!PORT) { console.error('set PGPORT (run via run-add-list-item-test.sh)'); process.exit(2); }
const db = new pg.Client({ host: '127.0.0.1', port: PORT, user: 'postgres', database: 'postgres' });

let pass = 0, fail = 0;
const ok = (c, m) => { c ? (pass++, console.log('  PASS', m)) : (fail++, console.log('  FAIL', m)); };

// The handler runs inside a txn (it uses pg_advisory_xact_lock). Drive each command in its own txn.
async function run(command, args) {
  await db.query('begin');
  try { const r = await execute(db, command, args); await db.query('commit'); return r; }
  catch (e) { await db.query('rollback'); return { ok: false, error: String(e.message) }; }
}
const items = async (listId) => (await db.query(`select item_name, requested_qty, status from asdair.shopping_list_items where list_id=$1 order by item_name`, [listId])).rows;

async function main() {
  await db.connect();
  // Hermetic setup: the CI cockpit-db job runs the migration-chain test FIRST in this SAME database,
  // which leaves a MINIMAL `asdair` stub (e.g. shopping_list_items without `note`, no `orders`). Since
  // 001 uses `create table if not exists`, that stub would shadow the real schema and the handler's
  // insert (which sets `note`) would fail with `column "note" does not exist`. Drop the schema first so
  // we always apply the REAL asdair schema cleanly and resolveHousehold sees only THIS test's household.
  await db.query('drop schema if exists asdair cascade');
  await db.query(fs.readFileSync(SCHEMA, 'utf8'));
  // regulars has no committed DDL (live-only) — minimal stub for the regression test.
  await db.query(`create table if not exists asdair.regulars (id bigint generated by default as identity primary key, household_id bigint not null references asdair.households(id), name text not null, active boolean default true)`);
  const hh = (await db.query(`insert into asdair.households (name, display_name) values ('household-a','A') returning id`)).rows[0].id;
  console.log(`[setup] synthetic household ${hh}\n`);

  console.log('1) add_list_item insert:');
  const r1 = await run('add_list_item', { item_name: 'Milk', requested_qty: 2, status: 'requested' });
  ok(r1.ok && r1.action === 'inserted', 'inserted a draft item');
  const listId = r1.list_id;
  ok((await items(listId)).length === 1, 'one item on the draft list');

  console.log('2) idempotency — replay the same intent:');
  const r2 = await run('add_list_item', { item_name: 'Milk', requested_qty: 2, status: 'requested' });
  ok(r2.ok && r2.action === 'unchanged' && r2.corrected === false, 'replay = unchanged (no correction)');
  ok((await items(listId)).length === 1, 'still one item (no duplicate)');

  console.log('3) correction — same item, new qty:');
  const r3 = await run('add_list_item', { item_name: 'milk', requested_qty: 3, status: 'requested' });
  ok(r3.ok && r3.action === 'corrected' && r3.corrected === true, 'a new qty corrects the SAME item');
  const milk = (await items(listId)).find((i) => i.item_name.toLowerCase() === 'milk');
  ok(Number(milk.requested_qty) === 3, 'qty updated to 3');
  ok((await items(listId)).length === 1, 'still one item (case-insensitive match, no duplicate)');

  console.log('4) ambiguous item preserved as needs_decision:');
  const r4 = await run('add_list_item', { item_name: '1.5 flour', requested_qty: null, status: 'needs_decision', note: 'needs review: conflicting quantity' });
  ok(r4.ok && r4.status === 'needs_decision', 'ambiguous item stored needs_decision (durable, awaits human)');
  ok((await items(listId)).find((i) => i.status === 'needs_decision'), 'a needs_decision row exists on the list');

  console.log('5) validation + allowlist fail closed (never executed):');
  ok((await run('add_list_item', { item_name: '', status: 'requested' })).ok === false, 'empty item_name rejected');
  ok((await run('add_list_item', { item_name: 'X', requested_qty: 500, status: 'requested' })).ok === false, 'qty out of range rejected');
  ok((await run('add_list_item', { item_name: 'X', status: 'checkout' })).ok === false, 'bad status rejected');
  ok((await run('checkout_and_pay', { total: 999 })).error === 'command not in allowlist (not executed)', 'checkout/pay is NOT in the allowlist — never executed');

  console.log('6) regression — add_regular_to_next_week still works:');
  const reg = (await db.query(`insert into asdair.regulars (household_id, name) values ($1,'Eggs') returning id`, [hh])).rows[0].id;
  const r6 = await run('add_regular_to_next_week', { regular_id: reg, qty: 6 });
  ok(r6.ok && r6.regular_name === 'Eggs', 'add_regular_to_next_week unaffected by the refactor');

  console.log('7) list_date is honoured — an item for a specific date lands on that specific list:');
  const r7 = await run('add_list_item', { item_name: 'Bread', requested_qty: 1, status: 'requested', list_date: '2026-08-10' });
  ok(r7.ok, 'add with an explicit list_date succeeds');
  const dated = (await db.query(`select to_char(sl.list_date,'YYYY-MM-DD') as list_date from asdair.shopping_list_items sli join asdair.shopping_lists sl on sl.id=sli.list_id where sli.list_id=$1 and lower(sli.item_name)='bread'`, [r7.list_id])).rows[0];
  ok(dated && dated.list_date === '2026-08-10', 'the item is on the 2026-08-10 draft list, not the default one');
  ok(r7.list_id !== listId, 'a distinct list was used for the distinct date');
  ok((await run('add_list_item', { item_name: 'X', status: 'requested', list_date: 'not-a-date' })).ok === false, 'a malformed list_date is rejected');

  console.log('8) no checkout/order side effect — the orders table is untouched:');
  ok((await db.query(`select count(*)::int n from asdair.orders`)).rows[0].n === 0, 'no order row was ever created (add-only, no checkout)');

  console.log(`\nRESULT: ${fail === 0 ? 'PASS ✓' : 'FAIL ✗'} — ${pass} passed, ${fail} failed`);
}
main().catch((e) => { console.error('[add-list-item] error', e.message); fail++; }).finally(async () => { await db.end().catch(() => {}); process.exit(fail === 0 ? 0 : 1); });
