// BUILD-002 WP5 — add_list_item handler proof against a THROWAWAY Postgres with the real asdair schema.
//   (run via run-add-list-item-test.sh — it provisions the cluster + sets PGPORT)
// Proves the Shopper write handler on synthetic data: insert, idempotency, correction, ambiguous
// (needs_decision), validation, allowlist, regression (add_regular still works), and no checkout/order
// side effect. NEVER touches Warwick's live household DB — only the final real write is Warwick-gated.
//
// WP-B15-16 — THE SHOP OWNS THE LIST, NOT THE DATE.
// Extended to prove migration 019. The offline double (services/asdair/pipeline/test/fakePg.js) CANNOT
// prove this and would go green on a fix real Postgres rejects: it models no uniqueness on
// shopping_lists at all. Only a real server enforces the indexes this change turns on, so this file is
// the proof route and the assertions below are named (a)-(g) after the schema decision packet
// (Deliverables/2026-08-10-silas-shopping-lists-identity-decision.md §8) so they cannot be fudged.
//
// THE REGRESSION. Set ASDAIR_DBTEST_WITHOUT_019=1 to apply the chain WITHOUT 019. Assertion (d) — the
// same item name, on the same date, under two different shops — then FAILS, because the two shops are
// forced onto one list row and the second write silently clobbers the first's quantity. That is the
// live defect of 2026-08-10. This mode NEVER inverts a result and never exits 0 on a failure: it
// reports exactly what happened, so it cannot become a knob that manufactures a green.
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';
import pg from 'pg';
import { execute } from './asdairCommands.mjs';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ASDAIR_DB = path.resolve(HERE, '..', '..', 'asdair', 'db');
const MYPKA_DB = path.resolve(HERE, '..', 'db', 'mypka');
const SCHEMA = path.join(ASDAIR_DB, '001_asdair_schema.sql');
const M019 = path.join(ASDAIR_DB, '019_shopping_list_shop_identity.sql');
const WITHOUT_019 = process.env.ASDAIR_DBTEST_WITHOUT_019 === '1';
const PORT = Number(process.env.PGPORT || 0);
if (!PORT) { console.error('set PGPORT (run via run-add-list-item-test.sh)'); process.exit(2); }
const db = new pg.Client({ host: '127.0.0.1', port: PORT, user: 'postgres', database: 'postgres' });

let pass = 0, fail = 0;
const ok = (c, m) => { c ? (pass++, console.log('  PASS', m)) : (fail++, console.log('  FAIL', m)); };

// Silas's seven named assertions, tracked by letter so the return can report each one BY NAME.
const NAMED = { a: null, b: null, c: null, d: null, e: null, f: null, g: null };
const okNamed = (letter, cond, m) => {
  NAMED[letter] = NAMED[letter] === 'FAIL' ? 'FAIL' : (cond ? 'PASS' : 'FAIL');
  ok(cond, `(${letter}) ${m}`);
};
const skipNamed = (letter, why) => { NAMED[letter] = `SKIPPED (${why})`; console.log(`  SKIP (${letter}) ${why}`); };

// The handler runs inside a txn (it uses pg_advisory_xact_lock). Drive each command in its own txn.
async function run(command, args, client = db) {
  await client.query('begin');
  try { const r = await execute(client, command, args); await client.query('commit'); return r; }
  catch (e) { await client.query('rollback'); return { ok: false, error: String(e.message), code: e.code }; }
}
const items = async (listId) => (await db.query(`select item_name, requested_qty, status from asdair.shopping_list_items where list_id=$1 order by item_name`, [listId])).rows;

// A raw statement whose FAILURE is the thing under test. Returns the SQLSTATE, or null on success.
async function errCode(sql, params = []) {
  await db.query('begin');
  try { await db.query(sql, params); await db.query('commit'); return null; }
  catch (e) { await db.query('rollback'); return e.code || 'unknown'; }
}

// The migration chain these assertions actually need. The order's "001 + 006 + 019" was short: 006
// declares a dependency on 001 AND 004 (regulars, stubbed below as it has no committed DDL in this
// harness's lineage), 008 is part of the decision packet's chain, and assertion (e) additionally needs
// the cockpit role + grant migrations, which live under services/control-plane/db/mypka/.
async function applyChain({ include019 }) {
  await db.query('drop schema if exists asdair cascade');
  await db.query(fs.readFileSync(SCHEMA, 'utf8'));
  // regulars has no committed DDL (live-only) — minimal stub for the regression test.
  await db.query(`create table if not exists asdair.regulars (id bigint generated by default as identity primary key, household_id bigint not null references asdair.households(id), name text not null, active boolean default true)`);
  for (const f of ['006_shop_control_surface.sql', '008_shop_line_interpretation.sql']) {
    await db.query(fs.readFileSync(path.join(ASDAIR_DB, f), 'utf8'));
  }
  if (include019) await db.query(fs.readFileSync(M019, 'utf8'));
}

const shop = async (householdId, ref, status) =>
  (await db.query(`insert into asdair.shop (household_id, shop_ref, status, source_kind) values ($1,$2,$3,'text') returning id`, [householdId, ref, status])).rows[0].id;

async function main() {
  await db.connect();
  const notices = [];
  db.on('notice', (n) => notices.push(String(n.message || '')));

  if (WITHOUT_019) {
    console.log('*** ASDAIR_DBTEST_WITHOUT_019=1 — REGRESSION MODE ***');
    console.log('*** The chain is applied WITHOUT migration 019. Assertion (d) is EXPECTED to fail:');
    console.log('*** that failure IS the defect this migration closes. Nothing is inverted and this');
    console.log('*** mode can never exit 0 on a failing assertion.\n');
  }
  // Hermetic setup: the CI cockpit-db job runs the migration-chain test FIRST in this SAME database,
  // which leaves a MINIMAL `asdair` stub (e.g. shopping_list_items without `note`, no `orders`). Since
  // 001 uses `create table if not exists`, that stub would shadow the real schema and the handler's
  // insert (which sets `note`) would fail with `column "note" does not exist`. Drop the schema first so
  // we always apply the REAL asdair schema cleanly and resolveHousehold sees only THIS test's household.
  await applyChain({ include019: !WITHOUT_019 });
  const hh = (await db.query(`insert into asdair.households (name, display_name) values ('household-a','A') returning id`)).rows[0].id;
  console.log(`[setup] synthetic household ${hh}  |  chain: 001 + regulars stub + 006 + 008${WITHOUT_019 ? '  (019 DELIBERATELY ABSENT)' : ' + 019'}\n`);

  console.log('1) add_list_item insert:');
  const r1 = await run('add_list_item', { item_name: 'Milk', requested_qty: 2, status: 'requested' });
  ok(r1.ok && r1.action === 'inserted', 'inserted a draft item');
  const listId = r1.list_id;
  ok((await items(listId)).length === 1, 'one item on the draft list');

  console.log('2) idempotency — replay the same intent:');
  const r2 = await run('add_list_item', { item_name: 'Milk', requested_qty: 2, status: 'requested' });
  ok(r2.ok && r2.action === 'unchanged' && r2.corrected === false, 'replay = unchanged (no correction)');
  ok((await items(listId)).length === 1, 'still one item (no duplicate)');

  console.log('3) correction — same item, new qty:');
  const r3 = await run('add_list_item', { item_name: 'milk', requested_qty: 3, status: 'requested' });
  ok(r3.ok && r3.action === 'corrected' && r3.corrected === true, 'a new qty corrects the SAME item');
  const milk = (await items(listId)).find((i) => i.item_name.toLowerCase() === 'milk');
  ok(Number(milk.requested_qty) === 3, 'qty updated to 3');
  ok((await items(listId)).length === 1, 'still one item (case-insensitive match, no duplicate)');

  console.log('4) ambiguous item preserved as needs_decision:');
  const r4 = await run('add_list_item', { item_name: '1.5 flour', requested_qty: null, status: 'needs_decision', note: 'needs review: conflicting quantity' });
  ok(r4.ok && r4.status === 'needs_decision', 'ambiguous item stored needs_decision (durable, awaits human)');
  ok((await items(listId)).find((i) => i.status === 'needs_decision'), 'a needs_decision row exists on the list');

  console.log('5) validation + allowlist fail closed (never executed):');
  ok((await run('add_list_item', { item_name: '', status: 'requested' })).ok === false, 'empty item_name rejected');
  ok((await run('add_list_item', { item_name: 'X', requested_qty: 500, status: 'requested' })).ok === false, 'qty out of range rejected');
  ok((await run('add_list_item', { item_name: 'X', status: 'checkout' })).ok === false, 'bad status rejected');
  ok((await run('checkout_and_pay', { total: 999 })).error === 'command not in allowlist (not executed)', 'checkout/pay is NOT in the allowlist — never executed');
  // WP-B15-16: a malformed shop_id must fail closed, never fall back to the date-keyed lane.
  ok((await run('add_list_item', { item_name: 'X', status: 'requested', shop_id: 'not-a-number' })).ok === false, 'malformed shop_id rejected (never silently date-keyed)');
  ok((await run('add_list_item', { item_name: 'X', status: 'requested', shop_id: 0 })).ok === false, 'shop_id 0 rejected');

  console.log('6) regression — add_regular_to_next_week still works:');
  const reg = (await db.query(`insert into asdair.regulars (household_id, name) values ($1,'Eggs') returning id`, [hh])).rows[0].id;
  const r6 = await run('add_regular_to_next_week', { regular_id: reg, qty: 6 });
  ok(r6.ok && r6.regular_name === 'Eggs', 'add_regular_to_next_week unaffected by the refactor');

  console.log('7) list_date is honoured — an item for a specific date lands on that specific list:');
  const r7 = await run('add_list_item', { item_name: 'Bread', requested_qty: 1, status: 'requested', list_date: '2026-08-10' });
  ok(r7.ok, 'add with an explicit list_date succeeds');
  const dated = (await db.query(`select to_char(sl.list_date,'YYYY-MM-DD') as list_date from asdair.shopping_list_items sli join asdair.shopping_lists sl on sl.id=sli.list_id where sli.list_id=$1 and lower(sli.item_name)='bread'`, [r7.list_id])).rows[0];
  ok(dated && dated.list_date === '2026-08-10', 'the item is on the 2026-08-10 draft list, not the default one');
  ok(r7.list_id !== listId, 'a distinct list was used for the distinct date');
  ok((await run('add_list_item', { item_name: 'X', status: 'requested', list_date: 'not-a-date' })).ok === false, 'a malformed list_date is rejected');

  console.log('8) no checkout/order side effect — the orders table is untouched:');
  ok((await db.query(`select count(*)::int n from asdair.orders`)).rows[0].n === 0, 'no order row was ever created (add-only, no checkout)');

  // ── WP-B15-16 / migration 019 — the named assertions ──────────────────────────────────────────
  const DATE = '2026-09-07';
  const shopA = await shop(hh, 'SHOP-2026-09-07', 'PROCESSING');
  const shopB = await shop(hh, 'SHOP-2026-09-07-M64', 'PROCESSING');

  console.log('\n9) (a) two shops, one household, ONE DATE — each owns its own list:');
  if (WITHOUT_019) {
    // Without 019 there is no shop_id column, so the only expressible form is two lists on one date —
    // which is exactly what the old constraint refuses, and exactly why two shops had to share a row.
    await db.query(`insert into asdair.shopping_lists (household_id, status, list_date) values ($1,'next_week_draft',$2)`, [hh, DATE]);
    const code = await errCode(`insert into asdair.shopping_lists (household_id, status, list_date) values ($1,'next_week_draft',$2)`, [hh, DATE]);
    okNamed('a', code === null, `two lists for one household+date both insert  [observed SQLSTATE ${code} — the old unique constraint refusing the second shop a list of its own]`);
  } else {
    const l1 = await errCode(`insert into asdair.shopping_lists (household_id, status, list_date, shop_id) values ($1,'next_week_draft',$2,$3)`, [hh, DATE, shopA]);
    const l2 = await errCode(`insert into asdair.shopping_lists (household_id, status, list_date, shop_id) values ($1,'next_week_draft',$2,$3)`, [hh, DATE, shopB]);
    okNamed('a', l1 === null && l2 === null, 'two lists, same household, same list_date, DIFFERENT shop_id — both insert');
  }

  console.log('10) (b) one list per shop is enforced by Postgres, not by application code:');
  if (WITHOUT_019) skipNamed('b', 'not expressible without 019 — the shop_id column does not exist');
  else {
    const dup = await errCode(`insert into asdair.shopping_lists (household_id, status, list_date, shop_id) values ($1,'next_week_draft',$2,$3)`, [hh, '2026-09-14', shopA]);
    okNamed('b', dup === '23505', `a second list for the SAME shop_id is refused by the database  [SQLSTATE ${dup}]`);
  }

  console.log('11) (c) the unowned lane keeps exactly the guarantee it has today:');
  await db.query(`insert into asdair.shopping_lists (household_id, status, list_date) values ($1,'next_week_draft','2026-10-05')`, [hh]);
  const unowned = await errCode(`insert into asdair.shopping_lists (household_id, status, list_date) values ($1,'next_week_draft','2026-10-05')`, [hh]);
  okNamed('c', unowned === '23505', `two shop_id IS NULL lists for one household+date are refused  [SQLSTATE ${unowned}]`);

  console.log('12) (d) THE DEFECT ITSELF — same item, same date, two shops, two independent rows:');
  const dA = await run('add_list_item', { item_name: 'Milk', requested_qty: 2, status: 'requested', list_date: DATE, ...(WITHOUT_019 ? {} : { shop_id: shopA }) });
  const dB = await run('add_list_item', { item_name: 'Milk', requested_qty: 1, status: 'requested', list_date: DATE, ...(WITHOUT_019 ? {} : { shop_id: shopB }) });
  const rowsA = dA.ok ? await items(dA.list_id) : [];
  const rowsB = dB.ok ? await items(dB.list_id) : [];
  const milkA = rowsA.find((i) => i.item_name.toLowerCase() === 'milk');
  const milkB = rowsB.find((i) => i.item_name.toLowerCase() === 'milk');
  const twoRows = dA.ok && dB.ok && dA.list_id !== dB.list_id
    && milkA && milkB && Number(milkA.requested_qty) === 2 && Number(milkB.requested_qty) === 1;
  okNamed('d', twoRows, twoRows
    ? 'TWO independent rows: shop A keeps qty 2 while shop B holds qty 1 — neither shop can clobber the other'
    : `ONE shared row — shop A asked for 2, shop B asked for 1, the row now reads ${milkA ? milkA.requested_qty : 'n/a'}. `
      + `A unit vanished from the basket silently. [list_id A=${dA.list_id} B=${dB.list_id}]`);

  console.log('13) (f) 019 is idempotent — re-applying it is a no-op:');
  if (WITHOUT_019) skipNamed('f', 'the migration is deliberately not applied in regression mode');
  else {
    let reapplyError = null;
    try { await db.query(fs.readFileSync(M019, 'utf8')); } catch (e) { reapplyError = e.message; }
    okNamed('f', reapplyError === null, `019 re-applied cleanly${reapplyError ? ` — ERROR: ${reapplyError}` : ' (no error, no duplicate index)'}`);
  }

  // ── (e) the whole sequence as cp_worker — proving no grant is missing ─────────────────────────
  console.log('14) (e) the same write path executed as cp_worker (least-privilege), not as superuser:');
  if (WITHOUT_019) skipNamed('e', 'grant proof belongs to the 019 chain');
  else {
    // The password is GENERATED AT RUNTIME and applied to this disposable cluster only. 020 creates
    // cp_worker with NO password on purpose ("a password in a committed migration would be a leaked
    // secret") — so nothing is committed here either, and there is no literal for a scanner to find
    // or a reader to mistake for a real credential. It dies with the cluster.
    const pw = crypto.randomBytes(24).toString('hex');
    if (!/^[0-9a-f]{48}$/.test(pw)) throw new Error('generated password is not the expected hex shape');
    let worker = null;
    try {
      await db.query(fs.readFileSync(path.join(MYPKA_DB, '020_cockpit_roles.sql'), 'utf8'));
      // directus_sys is created by the Directus INSTALL, not by any migration, so it is live-only —
      // the same situation as the regulars stub above. 040:35 grants cp_directus usage on it, and the
      // whole file is wrapped in begin;/commit;, so without this stub 040 aborts as a unit and NONE of
      // the asdair grants it carries are applied. The stub is empty on purpose: it exists so the
      // COMMITTED grants can be applied verbatim, never to stand in for one.
      await db.query('create schema if not exists directus_sys');
      // 030 creates asdair.command_request, which 040's GRANT lines reference unguarded (its REVOKE
      // lines are to_regclass-guarded; the grants are not). Established by reading the files, not by
      // guessing at the chain.
      await db.query(fs.readFileSync(path.join(MYPKA_DB, '030_command_request.sql'), 'utf8'));
      await db.query(fs.readFileSync(path.join(MYPKA_DB, '040_cockpit_grants.sql'), 'utf8'));
      await db.query(`alter role cp_worker login password '${pw}'`);
      worker = new pg.Client({ host: '127.0.0.1', port: PORT, user: 'cp_worker', password: pw, database: 'postgres' });
      await worker.connect();
      const shopE = await shop(hh, 'SHOP-2026-11-02', 'PROCESSING');
      const rE = await run('add_list_item', { item_name: 'Butter', requested_qty: 1, status: 'requested', list_date: '2026-11-02', shop_id: shopE, household: hh }, worker);
      const ownedByShop = rE.ok
        ? (await db.query('select shop_id from asdair.shopping_lists where id=$1', [rE.list_id])).rows[0].shop_id
        : null;
      okNamed('e', rE.ok && String(ownedByShop) === String(shopE),
        rE.ok ? 'cp_worker inserted a SHOP-OWNED list and its item — the FK check against asdair.shop needs no extra privilege'
          : `cp_worker was refused: ${rE.error}`);
    } catch (e) {
      okNamed('e', false, `cp_worker path could not be exercised: ${e.message}`);
      // 040 is wrapped in begin;/commit;, so a mid-file failure leaves an ABORTED transaction open on
      // this connection and every later phase dies with "current transaction is aborted". That is how
      // one failed grant silently swallowed the entire (g) backfill proof. Clear it, so a failure
      // reports itself and nothing downstream is lost.
      await db.query('rollback').catch(() => {});
    } finally { if (worker) await worker.end().catch(() => {}); }
  }

  // ── (g) the backfill: the LIVE shop wins a shared row, and not one item moves ─────────────────
  console.log('15) (g) backfill — two shops on ONE list, the LIVE shop becomes the owner:');
  if (WITHOUT_019) skipNamed('g', 'the backfill proof applies 019 itself');
  else {
    // Rebuild WITHOUT 019 and reproduce the real 2026-08-10 shape: a CANCELLED shop and a live one,
    // both pointing at the same list, with items already materialised on it.
    await applyChain({ include019: false });
    const h2 = (await db.query(`insert into asdair.households (name, display_name) values ('household-g','G') returning id`)).rows[0].id;
    const dead = await shop(h2, 'SHOP-2026-08-10', 'CANCELLED');
    const live = await shop(h2, 'SHOP-2026-08-10-M64', 'PROCESSING');
    const shared = (await db.query(`insert into asdair.shopping_lists (household_id, status, list_date) values ($1,'next_week_draft','2026-08-10') returning id`, [h2])).rows[0].id;
    await db.query('update asdair.shop set list_id=$1 where id in ($2,$3)', [shared, dead, live]);
    await db.query(`insert into asdair.shopping_list_items (list_id,item_name,requested_qty,status,note) values ($1,'Milk',2,'requested','x'), ($1,'Eggs',6,'requested','x')`, [shared]);
    const before = (await db.query('select id, list_id from asdair.shopping_list_items order by id')).rows
      .map((r) => `${r.id}:${r.list_id}`).join(',');

    notices.length = 0;
    await db.query(fs.readFileSync(M019, 'utf8'));

    const owner = (await db.query('select shop_id from asdair.shopping_lists where id=$1', [shared])).rows[0].shop_id;
    const after = (await db.query('select id, list_id from asdair.shopping_list_items order by id')).rows
      .map((r) => `${r.id}:${r.list_id}`).join(',');
    const deadPointer = (await db.query('select list_id from asdair.shop where id=$1', [dead])).rows[0].list_id;
    const listCount = (await db.query('select count(*)::int n from asdair.shopping_lists')).rows[0].n;

    okNamed('g', String(owner) === String(live), `the LIVE shop owns the shared row (owner=${owner}, live=${live}, cancelled=${dead})`);
    okNamed('g', after === before, `not one shopping_list_items row changed its list_id  [before ${before} | after ${after}]`);
    okNamed('g', String(deadPointer) === String(shared), 'the cancelled shop KEEPS its shop.list_id pointer — its history still reads, it is simply not the owner');
    okNamed('g', listCount === 1, 'no list row was added, moved or orphaned by the migration');
    okNamed('g', notices.some((m) => m.includes('019:') && m.includes('more than one shop')),
      `the migration SAID SO rather than staying silent  [notice: ${notices.find((m) => m.includes('019:')) || 'NONE RAISED'}]`);
  }

  console.log('\nSILAS ASSERTIONS (schema decision packet §8):');
  for (const [k, v] of Object.entries(NAMED)) console.log(`  (${k}) ${v === null ? 'NOT REACHED' : v}`);
  console.log(`\nRESULT: ${fail === 0 ? 'PASS ✓' : 'FAIL ✗'} — ${pass} passed, ${fail} failed`);
  if (WITHOUT_019) {
    console.log('\n*** REGRESSION MODE: the failures above are the DEFECT, observed on the schema');
    console.log('*** without migration 019. This run is EXPECTED to exit non-zero.');
  }
}
main().catch((e) => { console.error('[add-list-item] error', e.message); fail++; }).finally(async () => { await db.end().catch(() => {}); process.exit(fail === 0 ? 0 : 1); });
