// tools/wo/dispatch-guard.test.mjs — proofs for 4F CAPA item 8.
//
// The claim under test is narrow and load-bearing: THE DISPATCH EVENT ITSELF REFUSES AN
// UNREADY WORK ORDER. Everything here is written against the real `PreToolUse` payload shape
// the host sends, not against a convenient internal API — a guard proven only through its own
// helpers proves nothing about the production event.
//
// Two disciplines, inherited from envelope.test.mjs and not re-argued here:
//   1. Invariants are pinned to literals HELD IN THIS FILE.
//   2. Every control is MUTATION-TESTED. A check no test can fail is decorative.
//
// Mutants load through a `data:` URL, so this suite writes nothing outside the declared file
// surface. dispatch-guard.mjs has ONE relative import, so the mutant's specifier is rewritten
// to an absolute file URL before loading — the alternative (writing mutants to disk) would put
// bytes outside the surface for no gain.

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, writeFileSync, mkdtempSync } from 'node:fs';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { dirname, join } from 'node:path';
import { tmpdir } from 'node:os';
import { execFileSync } from 'node:child_process';

import * as G from './dispatch-guard.mjs';
import * as E from './envelope.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = join(HERE, '..', '..');
const SRC_PATH = join(HERE, 'dispatch-guard.mjs');
const norm = (s) => s.replace(/\r\n/g, '\n');
const SRC = norm(readFileSync(SRC_PATH, 'utf8'));
const ENVELOPE_URL = pathToFileURL(join(HERE, 'envelope.mjs')).href;

// ---------------------------------------------------------------------------
// PINNED LITERALS — held here, never read back off the module under test.
// ---------------------------------------------------------------------------

const L_DISPATCH_TOOL = 'Task';
const L_ORDER_MARKER = 'GENERATED by tools/wo/envelope.mjs';
const L_DENY = 'deny';
const L_HOOK_EVENT = 'PreToolUse';
// `governance_head` is deliberately NOT a shape signal: root CLAUDE.md requires EVERY
// dispatch to name it, so treating it as one would deny every Veritas and Pax dispatch.
const L_NOT_A_SHAPE_SIGNAL = 'governance_head';

// ---------------------------------------------------------------------------
// Mutation harness.
// ---------------------------------------------------------------------------

async function loadMutant(find, replace) {
  assert.ok(SRC.includes(find), `mutation target absent from source: ${JSON.stringify(find)}`);
  const mutated = SRC.replace(find, replace).replace("from './envelope.mjs'", `from '${ENVELOPE_URL}'`);
  assert.notEqual(mutated, SRC, 'mutation did not change the source');
  return import(`data:text/javascript;base64,${Buffer.from(mutated, 'utf8').toString('base64')}`);
}

async function assertMutantBreaks(mutant, fn, label) {
  let broke = false;
  try {
    fn(mutant);
  } catch {
    broke = true;
  }
  assert.equal(broke, true, `MUTATION SURVIVED — the control is decorative: ${label}`);
}

// ---------------------------------------------------------------------------
// Fixtures — real generated orders, produced by the real generator.
// ---------------------------------------------------------------------------

/**
 * V4-7 hermeticity, same approach as envelope.test.mjs: a clean `git archive` export has no
 * `.git`, so head verification is redirected to a throwaway temp repository. Never `git init`
 * inside the source tree — that contaminates the fixture.
 */
let HEAD = null;
function headSha() {
  if (HEAD) return HEAD;
  try {
    HEAD = execFileSync('git', ['-C', REPO, 'rev-parse', 'HEAD'], { encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }).trim();
    return HEAD;
  } catch {
    const fixture = mkdtempSync(join(tmpdir(), 'wo-dispatch-git-'));
    execFileSync('git', ['init'], { cwd: fixture, stdio: 'ignore' });
    execFileSync('git', ['config', 'user.email', 'wo-test@example.com'], { cwd: fixture, stdio: 'ignore' });
    execFileSync('git', ['config', 'user.name', 'wo-test'], { cwd: fixture, stdio: 'ignore' });
    writeFileSync(join(fixture, 'a.txt'), 'head\n');
    execFileSync('git', ['add', 'a.txt'], { cwd: fixture, stdio: 'ignore' });
    execFileSync('git', ['commit', '-m', 'wo-dispatch-test'], { cwd: fixture, stdio: 'ignore' });
    process.env.WO_TEST_GIT_CWD = fixture;
    process.env.WO_TEST_GIT_ALLOW_REDIRECT = '1';
    HEAD = execFileSync('git', ['-C', fixture, 'rev-parse', 'HEAD'], { encoding: 'utf8' }).trim();
    return HEAD;
  }
}

function generatedOrder() {
  const r = E.generateOrder({
    root: REPO,
    owner: 'keel',
    governanceHead: headSha(),
    surfaces: ['tools/wo/envelope.mjs'],
    now: new Date('2026-08-09T00:00:00.000Z'),
  });
  assert.equal(r.ok, true, 'the fixture generator run must succeed');
  return r.text;
}

function authoredOrder() {
  return generatedOrder()
    .replace(/^(\s*)([a-z_]+): AUTHOR REQUIRED — .*$/gm, '$1$2: authored-for-fixture')
    .replace(/^# AUTHOR REQUIRED — .*$/gm, '# WO-FIXTURE — title')
    .replace(/^- AUTHOR REQUIRED — .*$/gm, '- authored for fixture')
    .replace(/^AUTHOR REQUIRED — AC1\.\.ACn$/m, 'AC1 — the guard refuses an unready order.')
    .replace(/^AUTHOR REQUIRED — .*$/gm, 'authored for fixture');
}

/** The exact payload shape the host sends a PreToolUse hook. */
function payload(prompt, { tool = L_DISPATCH_TOOL, cwd = REPO } = {}) {
  return JSON.stringify({
    session_id: 'fixture',
    hook_event_name: L_HOOK_EVENT,
    tool_name: tool,
    cwd,
    tool_input: { subagent_type: 'keel', description: 'implement the work package', prompt },
  });
}

function hookOutput(raw, opts = {}) {
  return G.toHookOutput(G.runHook(raw, opts));
}

// ===========================================================================
// The two refusals.
// ===========================================================================

test('an UNREADY order pasted into the dispatch is DENIED at the dispatch event', () => {
  const out = hookOutput(payload(`Keel: implement this.\n\n${generatedOrder()}`));
  assert.ok(out, 'an unready order must not pass the dispatch event silently');
  assert.equal(out.hookSpecificOutput.hookEventName, L_HOOK_EVENT);
  assert.equal(out.hookSpecificOutput.permissionDecision, L_DENY);
  assert.match(out.hookSpecificOutput.permissionDecisionReason, /NOT READY/);
  assert.match(out.hookSpecificOutput.permissionDecisionReason, /AUTHOR REQUIRED/);
});

test('a READY order pasted into the dispatch is allowed through untouched', () => {
  assert.equal(hookOutput(payload(`Keel: implement this.\n\n${authoredOrder()}`)), null);
});

test('a dispatch that is Work-Order-shaped but carries no generated order is DENIED', () => {
  const freeform = [
    'WORK ORDER — make the thing work',
    'governance_head: 8bc5340',
    'private_surface: none',
    'credential_scope: none',
    'live_authority: none',
    'Commit onto build-020/whatever.',
  ].join('\n');
  const out = hookOutput(payload(freeform));
  assert.ok(out, 'the free-form bypass is the failure item 8 exists to close');
  assert.equal(out.hookSpecificOutput.permissionDecision, L_DENY);
  assert.match(out.hookSpecificOutput.permissionDecisionReason, /carries no GENERATED Work Order/);
});

test('an ordinary non-Work-Order dispatch is NOT touched — the gate must not brick the estate', () => {
  const veritas = [
    'Veritas: Gate 1 on the ACTIVE SESSION WORK PACKAGE in',
    'Deliverables/2026-08-04-build-015-asdair-wayfinder-plan.md.',
    'governance head 8bc5340. Return a separate PASS/HOLD/FAIL per numbered functional',
    'requirement. Do not narrow the audit to an older product slice.',
  ].join('\n');
  const pax = 'Pax: research dispatch-time validation in comparable estates. governance head 8bc5340.';
  assert.equal(hookOutput(payload(veritas)), null, 'an assurance dispatch must pass');
  assert.equal(hookOutput(payload(pax)), null, 'a research dispatch must pass');
});

test('naming the governance head alone never makes a dispatch look like a Work Order', () => {
  const shape = G.looksLikeWorkOrder(`please review this at ${L_NOT_A_SHAPE_SIGNAL} 8bc5340 and report`);
  assert.equal(shape.shaped, false, 'every dispatch in this estate names the governance head');
  assert.equal(G.ENVELOPE_FIELD_TOKENS.includes(L_NOT_A_SHAPE_SIGNAL), false);
});

test('a non-dispatch tool is never guarded', () => {
  assert.equal(hookOutput(payload('anything at all', { tool: 'Bash' })), null);
  assert.deepEqual(G.DISPATCH_TOOLS, [L_DISPATCH_TOOL]);
});

// ===========================================================================
// Referencing an order by path — the ordinary dispatch shape.
// ===========================================================================

// The ordinary dispatch shape is "your order is <path>". These two use REAL banked orders
// from this repository rather than fixtures, so the by-path route is proven against the
// corpus the CAPA was written about.
const L_UNREADY_BANKED_ORDER = 'Deliverables/proofline/WO-2026-08-06-ac5-3-mack-machine.md';
const L_READY_BANKED_ORDER = 'Deliverables/2026-08-09-WO-B15-C4-browser-contract-executable.md';

test('an UNREADY order referenced BY PATH is read and DENIED, not taken on trust', () => {
  const text = readFileSync(join(REPO, L_UNREADY_BANKED_ORDER), 'utf8');
  assert.equal(E.assessOrder(text, { root: REPO }).ready, false, 'precondition: this banked order is unready');
  const out = hookOutput(payload(`Keel: your order is ${L_UNREADY_BANKED_ORDER} — read it in full.`));
  assert.ok(out, 'an order named by path must be opened and assessed');
  assert.equal(out.hookSpecificOutput.permissionDecision, L_DENY);
  assert.match(out.hookSpecificOutput.permissionDecisionReason, new RegExp(L_UNREADY_BANKED_ORDER.replace(/[/.]/g, '\\$&')));
});

test('a READY order referenced BY PATH passes the dispatch event untouched', () => {
  const text = readFileSync(join(REPO, L_READY_BANKED_ORDER), 'utf8');
  assert.equal(E.assessOrder(text, { root: REPO }).ready, true, 'precondition: this banked order is ready');
  assert.equal(hookOutput(payload(`Keel: your order is ${L_READY_BANKED_ORDER} — read it in full.`)), null);
});

test('a cited document that is NOT an order is ignored — only the provenance marker counts', () => {
  const orders = G.collectOrders(
    'context: Deliverables/2026-08-04-proofline-wayfinder-plan.md and CLAUDE.md',
    [REPO],
  );
  assert.equal(orders.length, 0, 'a Wayfinder map is not a Work Order');
  assert.ok(!readFileSync(join(REPO, 'CLAUDE.md'), 'utf8').includes(L_ORDER_MARKER));
});

test('markdown references need a path separator — a bare filename is not a reference', () => {
  assert.deepEqual(G.markdownReferences('see notes.md and Deliverables/x.md'), ['Deliverables/x.md']);
});

// ===========================================================================
// Fail direction.
// ===========================================================================

test('unreadable input DEFERS rather than bricking every dispatch', () => {
  assert.equal(hookOutput(''), null);
  assert.equal(hookOutput('{not json'), null);
  assert.equal(hookOutput('[]'), null);
});

test('the guard emits ONLY on deny — a permitted dispatch produces no output at all', () => {
  assert.equal(G.toHookOutput({ decision: G.DECISION.DEFER, reason: 'fine' }), null);
  assert.equal(G.toHookOutput(null), null);
  const denied = G.toHookOutput({ decision: G.DECISION.DENY, reason: 'because' });
  assert.equal(denied.hookSpecificOutput.permissionDecision, L_DENY);
});

// ===========================================================================
// MUTATION PROOFS. Each asserts (a) the mutant genuinely stops refusing, and
// (b) the invariant that holds on the real module goes RED against the mutant.
// ===========================================================================

test('MUT-D1 the dispatch tool list emptied — nothing is guarded at all', async () => {
  const mutant = await loadMutant(
    "export const DISPATCH_TOOLS = ['Task'];",
    'export const DISPATCH_TOOLS = [];',
  );
  const raw = payload(`Keel: implement this.\n\n${generatedOrder()}`);
  assert.equal(mutant.toHookOutput(mutant.runHook(raw)), null, 'mutant should guard nothing');
  await assertMutantBreaks(
    mutant,
    (m) => assert.ok(m.toHookOutput(m.runHook(raw)), 'an unready order must be denied'),
    'MUT-D1 the subagent dispatch tool must be guarded',
  );
});

test('MUT-D2 the readiness verdict ignored — an unready order reaches the worker', async () => {
  const mutant = await loadMutant(
    '    const unready = assessed.filter((a) => !a.assessment.ready);',
    '    const unready = [];',
  );
  const raw = payload(`Keel: implement this.\n\n${generatedOrder()}`);
  assert.equal(mutant.toHookOutput(mutant.runHook(raw)), null, 'mutant should let the unready order through');
  await assertMutantBreaks(
    mutant,
    (m) => assert.ok(m.toHookOutput(m.runHook(raw))),
    'MUT-D2 an order the validator calls NOT READY must be denied at dispatch',
  );
});

test('MUT-D3 the free-form bypass reopened — a Work Order sent as prose is allowed', async () => {
  const mutant = await loadMutant(
    '  if (ORDER_PHRASE.test(String(text ?? \'\')) && fields.length >= 1) return { shaped: true, fields };',
    '  if (false) return { shaped: true, fields };',
  );
  const freeform = 'WORK ORDER — do the thing.\nprivate_surface: none\ngovernance_head: 8bc5340';
  const raw = payload(freeform);
  assert.equal(mutant.toHookOutput(mutant.runHook(raw)), null, 'mutant should reopen the bypass');
  await assertMutantBreaks(
    mutant,
    (m) => assert.ok(m.toHookOutput(m.runHook(raw))),
    'MUT-D3 sending a worker directly must not bypass the validator',
  );
});

test('MUT-D4 the provenance marker dropped from order detection — any cited doc becomes an order', async () => {
  const mutant = await loadMutant(
    '    if (!String(content).includes(ORDER_MARKER)) continue;',
    '    if (false) continue;',
  );
  const raw = payload('Veritas: review Deliverables/2026-08-04-proofline-wayfinder-plan.md at governance head 8bc5340.');
  const out = mutant.toHookOutput(mutant.runHook(raw));
  assert.ok(out, 'mutant should mistake a Wayfinder map for a Work Order and deny the assurance dispatch');
  await assertMutantBreaks(
    mutant,
    (m) => assert.equal(m.toHookOutput(m.runHook(raw)), null),
    'MUT-D4 only a document carrying the generator marker is a Work Order',
  );
});

test('MUT-D5 the deny output suppressed — the decision is made and never delivered', async () => {
  const mutant = await loadMutant(
    "  if (!result || result.decision !== DECISION.DENY) return null;",
    '  if (true) return null;',
  );
  const raw = payload(`Keel: implement this.\n\n${generatedOrder()}`);
  assert.equal(
    mutant.runHook(raw).decision,
    G.DECISION.DENY,
    'mutant still DECIDES to deny — it simply stops telling the host',
  );
  assert.equal(mutant.toHookOutput(mutant.runHook(raw)), null, 'mutant should swallow the refusal');
  await assertMutantBreaks(
    mutant,
    (m) => assert.ok(m.toHookOutput(m.runHook(raw))),
    'MUT-D5 a refusal the host never receives is not a refusal',
  );
});
