// tools/wo/dispatch-guard.test.mjs — proofs for 4F CAPA item 8.
//
// The claim under test is narrow and load-bearing: THE DISPATCH EVENT ITSELF REFUSES AN
// UNREADY WORK ORDER. Everything here is written against the real `PreToolUse` payload shape
// the host sends, not against a convenient internal API — a guard proven only through its own
// helpers proves nothing about the production event.
//
// Two disciplines, inherited from envelope.test.mjs and not re-argued here:
//   1. Invariants are pinned to literals HELD IN THIS FILE.
//   2. Every control is MUTATION-TESTED. A check no test can fail is decorative.
//
// Mutants load through a `data:` URL, so this suite writes nothing outside the declared file
// surface. dispatch-guard.mjs has ONE relative import, so the mutant's specifier is rewritten
// to an absolute file URL before loading — the alternative (writing mutants to disk) would put
// bytes outside the surface for no gain.

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, writeFileSync, mkdtempSync } from 'node:fs';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { dirname, join } from 'node:path';
import { tmpdir } from 'node:os';
import { execFileSync } from 'node:child_process';

import * as G from './dispatch-guard.mjs';
import * as E from './envelope.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = join(HERE, '..', '..');
const SRC_PATH = join(HERE, 'dispatch-guard.mjs');
const norm = (s) => s.replace(/\r\n/g, '\n');
const SRC = norm(readFileSync(SRC_PATH, 'utf8'));
const ENVELOPE_URL = pathToFileURL(join(HERE, 'envelope.mjs')).href;

// ---------------------------------------------------------------------------
// PINNED LITERALS — held here, never read back off the module under test.
// ---------------------------------------------------------------------------

const L_DISPATCH_TOOL = 'Task';
const L_ORDER_MARKER = 'GENERATED by tools/wo/envelope.mjs';
const L_DENY = 'deny';
const L_HOOK_EVENT = 'PreToolUse';

// ⛔ THE VALUE THIS GUARD MAY NEVER EMIT (Warwick, 2026-08-09: "It must never require me to
// click/approve routine dispatches."). Pinned HERE, outside the module under test, and
// CORROBORATED below against the estate's proven hook idiom so it is not a straw man: `ask` is
// a real, reachable, human-prompting value in this codebase today.
const L_PROMPTING_DECISION = 'ask';
const L_PERMITTED_HOOK_DECISIONS = ['deny'];
const L_WORKTREE_GUARD = 'tools/governor/worktree-guard.mjs';
// Every decision-producing return in dispatch-guard.mjs. Pinned so a NEW path cannot be added
// without this file going RED — enumeration, not inspection. A test that samples three paths
// says nothing about a fourth.
const L_DECISION_PATH_COUNT = 7;
// `governance_head` is deliberately NOT a shape signal: root CLAUDE.md requires EVERY
// dispatch to name it, so treating it as one would deny every Veritas and Pax dispatch.
const L_NOT_A_SHAPE_SIGNAL = 'governance_head';

// ---------------------------------------------------------------------------
// Mutation harness.
// ---------------------------------------------------------------------------

async function loadMutantAll(pairs) {
  let mutated = SRC;
  for (const [find, replace] of pairs) {
    assert.ok(mutated.includes(find), `mutation target absent from source: ${JSON.stringify(find)}`);
    mutated = mutated.replace(find, replace);
  }
  mutated = mutated.replace("from './envelope.mjs'", `from '${ENVELOPE_URL}'`);
  assert.notEqual(mutated, SRC, 'mutation did not change the source');
  return import(`data:text/javascript;base64,${Buffer.from(mutated, 'utf8').toString('base64')}`);
}

async function loadMutant(find, replace) {
  return loadMutantAll([[find, replace]]);
}

async function assertMutantBreaks(mutant, fn, label) {
  let broke = false;
  try {
    fn(mutant);
  } catch {
    broke = true;
  }
  assert.equal(broke, true, `MUTATION SURVIVED — the control is decorative: ${label}`);
}

// ---------------------------------------------------------------------------
// Fixtures — real generated orders, produced by the real generator.
// ---------------------------------------------------------------------------

/**
 * V4-7 hermeticity, same approach as envelope.test.mjs: a clean `git archive` export has no
 * `.git`, so head verification is redirected to a throwaway temp repository. Never `git init`
 * inside the source tree — that contaminates the fixture.
 */
let HEAD = null;
function headSha() {
  if (HEAD) return HEAD;
  try {
    HEAD = execFileSync('git', ['-C', REPO, 'rev-parse', 'HEAD'], { encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }).trim();
    return HEAD;
  } catch {
    const fixture = mkdtempSync(join(tmpdir(), 'wo-dispatch-git-'));
    execFileSync('git', ['init'], { cwd: fixture, stdio: 'ignore' });
    execFileSync('git', ['config', 'user.email', 'wo-test@example.com'], { cwd: fixture, stdio: 'ignore' });
    execFileSync('git', ['config', 'user.name', 'wo-test'], { cwd: fixture, stdio: 'ignore' });
    writeFileSync(join(fixture, 'a.txt'), 'head\n');
    execFileSync('git', ['add', 'a.txt'], { cwd: fixture, stdio: 'ignore' });
    execFileSync('git', ['commit', '-m', 'wo-dispatch-test'], { cwd: fixture, stdio: 'ignore' });
    process.env.WO_TEST_GIT_CWD = fixture;
    process.env.WO_TEST_GIT_ALLOW_REDIRECT = '1';
    HEAD = execFileSync('git', ['-C', fixture, 'rev-parse', 'HEAD'], { encoding: 'utf8' }).trim();
    return HEAD;
  }
}

function generatedOrder() {
  const r = E.generateOrder({
    root: REPO,
    owner: 'keel',
    governanceHead: headSha(),
    surfaces: ['tools/wo/envelope.mjs'],
    now: new Date('2026-08-09T00:00:00.000Z'),
  });
  assert.equal(r.ok, true, 'the fixture generator run must succeed');
  return r.text;
}

/**
 * The envelope keys the canonical template declares as LISTS. Pinned here so this fixture cannot
 * drift into producing a MALFORMED order: authoring `document_impact` as a bare scalar is the
 * exact defect the validator's malformed-field check exists to catch, and a fixture that does it
 * would make "a READY order passes" a proof about a broken order.
 */
const L_LIST_SHAPED_KEYS = ['blocking_dependencies', 'tags', 'document_impact'];

function authoredOrder() {
  return generatedOrder()
    .replace(new RegExp(`^(${L_LIST_SHAPED_KEYS.join('|')}): AUTHOR REQUIRED — .*$`, 'gm'), '$1: []')
    .replace(/^(\s*)([a-z_]+): AUTHOR REQUIRED — .*$/gm, '$1$2: authored-for-fixture')
    .replace(/^# AUTHOR REQUIRED — .*$/gm, '# WO-FIXTURE — title')
    .replace(/^- AUTHOR REQUIRED — .*$/gm, '- authored for fixture')
    .replace(/^AUTHOR REQUIRED — AC1\.\.ACn$/m, 'AC1 — the guard refuses an unready order.')
    .replace(/^AUTHOR REQUIRED — .*$/gm, 'authored for fixture');
}

/** The exact payload shape the host sends a PreToolUse hook. */
function payload(prompt, { tool = L_DISPATCH_TOOL, cwd = REPO } = {}) {
  return JSON.stringify({
    session_id: 'fixture',
    hook_event_name: L_HOOK_EVENT,
    tool_name: tool,
    cwd,
    tool_input: { subagent_type: 'keel', description: 'implement the work package', prompt },
  });
}

function hookOutput(raw, opts = {}) {
  return G.toHookOutput(G.runHook(raw, opts));
}

/** Source with comments removed — the header QUOTES worktree-guard's `ask` vocabulary on purpose. */
function codeOnly(src) {
  return src
    .split('\n')
    .filter((l) => !/^\s*\/\//.test(l))
    .join('\n')
    .replace(/\/\*[\s\S]*?\*\//g, '');
}

// ===========================================================================
// ⛔ AC1 — NO PATH MAY PUT A PROMPT IN FRONT OF WARWICK.
//
// Warwick, 2026-08-09: "This is an internal delegation-quality control, not a Warwick approval
// gate. It must never require me to click/approve routine dispatches."
//
// ENUMERATION, NOT INSPECTION. Three layers, because any one alone is a sample:
//   1. the value we forbid is proven REAL and human-prompting in this estate (not a straw man);
//   2. EVERY decision-producing return in the module is enumerated statically, and the count is
//      pinned, so a fourth path cannot be added silently;
//   3. every reachable path is then EXERCISED through the real hook entry point, and the
//      emission function is attacked directly with forged decisions.
// ===========================================================================

test('the forbidden value is REAL — `ask` is how this estate deliberately prompts Warwick', () => {
  // Corroborated against the proven idiom rather than asserted. If `ask` ever stops being the
  // prompting value, this test is where that shows up.
  const wg = norm(readFileSync(join(REPO, L_WORKTREE_GUARD), 'utf8'));
  assert.match(wg, /export const DECISION = \{[^}]*ASK: 'ask'[^}]*\};/, `${L_WORKTREE_GUARD} must still define ASK`);
  assert.match(wg, /const HOOK_DECISION = \{[\s\S]{0,200}\[DECISION\.ASK\]: 'ask',/, 'ASK must still be EMITTED as a permissionDecision');
  assert.match(wg, /PUSH_ASK_REASON = 'Warwick approval required for push to main\.'/, 'ASK must still be the value that asks Warwick');
});

test('AC1 — EVERY decision-producing path is enumerated, and none can emit the prompting value', () => {
  const code = codeOnly(SRC);
  const produced = [...code.matchAll(/\bdecision:\s*([A-Za-z0-9_.]+)/g)].map((m) => m[1]);
  assert.equal(
    produced.length,
    L_DECISION_PATH_COUNT,
    `decision-producing paths changed (${produced.length} found, ${L_DECISION_PATH_COUNT} pinned) — enumerate the new one and classify it before shipping`,
  );
  const permittedTokens = ['DECISION.DENY', 'DECISION.DEFER'];
  for (const token of produced) {
    assert.ok(permittedTokens.includes(token), `a decision path produces an unclassified value: ${token}`);
  }

  // The enum itself is closed: no ASK, no ALLOW. This guard denies, or it stands aside.
  assert.deepEqual(G.DECISION, { DENY: 'deny', DEFER: 'defer' });
  assert.equal(Object.isFrozen(G.DECISION), true, 'the decision enum must not be mutable at runtime');
  assert.equal(Object.values(G.DECISION).includes(L_PROMPTING_DECISION), false);
  assert.equal(Object.values(G.DECISION).includes('allow'), false, 'this guard never speaks for the human in either direction');

  // The emission set is closed and frozen.
  assert.deepEqual(G.PERMITTED_HOOK_DECISIONS, L_PERMITTED_HOOK_DECISIONS);
  assert.equal(Object.isFrozen(G.PERMITTED_HOOK_DECISIONS), true);
  assert.deepEqual(Object.values(G.HOOK_DECISION), L_PERMITTED_HOOK_DECISIONS);
  assert.equal(Object.isFrozen(G.HOOK_DECISION), true);
  assert.equal(G.HOOK_DECISION[L_PROMPTING_DECISION], undefined, 'nothing may map to the prompting value');
  assert.equal(G.PROMPTING_HOOK_DECISION, L_PROMPTING_DECISION);

  // The allowing literal appears nowhere in executable code at all.
  for (const forbidden of ["'allow'", '"allow"']) {
    assert.equal(code.includes(forbidden), false, `executable code carries the literal ${forbidden}`);
  }
  // The prompting literal appears EXACTLY ONCE, on the line that declares it forbidden, and the
  // constant is never referenced again — so it cannot be reached by any emission path.
  const askLines = code.split('\n').filter((l) => l.includes(`'${L_PROMPTING_DECISION}'`) || l.includes(`"${L_PROMPTING_DECISION}"`));
  assert.equal(askLines.length, 1, `the prompting literal appears on ${askLines.length} executable lines: ${askLines.join(' | ')}`);
  assert.match(askLines[0], /^export const PROMPTING_HOOK_DECISION = /);
  const uses = code.split('PROMPTING_HOOK_DECISION').length - 1;
  assert.equal(uses, 1, 'PROMPTING_HOOK_DECISION is declared for the test to pin, and must never be USED');
});

test('AC1 — every reachable path EXERCISED through the real hook entry point emits deny or nothing', () => {
  const unready = `Keel: implement this.\n\n${generatedOrder()}`;
  const ready = `Keel: implement this.\n\n${authoredOrder()}`;
  const shaped = 'WORK ORDER — do the thing.\nprivate_surface: none\ncredential_scope: none';

  // One scenario per enumerated decision path, named so a reader can check the mapping.
  const scenarios = [
    ['decideDispatch: not a dispatch tool', () => hookOutput(payload(unready, { tool: 'Bash' }))],
    ['decideDispatch: carried order is UNREADY', () => hookOutput(payload(unready))],
    ['decideDispatch: carried order is READY', () => hookOutput(payload(ready))],
    ['decideDispatch: Work-Order-shaped, no generated order', () => hookOutput(payload(shaped))],
    ['decideDispatch: not Work-Order-shaped at all', () => hookOutput(payload('Pax: research something. governance head 8bc5340.'))],
    ['runHook: input unreadable', () => hookOutput('{not json')],
    ['runHook: internal throw', () => hookOutput(payload(unready), {
      read: () => { throw new Error('forced internal failure'); },
    })],
  ];
  assert.equal(scenarios.length, L_DECISION_PATH_COUNT, 'one exercised scenario per enumerated decision path');

  let emitted = 0;
  let silent = 0;
  for (const [label, run] of scenarios) {
    const out = run();
    if (out === null) { silent++; continue; }
    const d = out.hookSpecificOutput.permissionDecision;
    assert.notEqual(d, L_PROMPTING_DECISION, `PATH PROMPTS WARWICK: ${label}`);
    assert.ok(L_PERMITTED_HOOK_DECISIONS.includes(d), `path emitted an unpermitted decision (${d}): ${label}`);
    emitted++;
  }
  assert.equal(emitted + silent, L_DECISION_PATH_COUNT);
  assert.ok(emitted > 0, 'a run in which nothing was ever emitted proves nothing about what is emitted');
});

test('AC1 — the emission function cannot be COERCED into prompting, whatever it is handed', () => {
  for (const decision of [L_PROMPTING_DECISION, 'allow', 'ASK', 'Deny', '', null, undefined, 0, 'defer']) {
    assert.equal(G.toHookOutput({ decision, reason: 'forged' }), null, `forged decision emitted: ${String(decision)}`);
  }
  // Inherited object properties must not become decisions — the frozen map is not enough on its
  // own, which is why the permitted-set check sits behind it.
  for (const decision of ['toString', 'constructor', '__proto__', 'hasOwnProperty']) {
    assert.equal(G.toHookOutput({ decision, reason: 'forged' }), null, `prototype key emitted: ${decision}`);
  }
  const real = G.toHookOutput({ decision: G.DECISION.DENY, reason: 'because' });
  assert.equal(real.hookSpecificOutput.permissionDecision, L_DENY, 'the one permitted emission must still work');
});

// ===========================================================================
// The two refusals.
// ===========================================================================

test('an UNREADY order pasted into the dispatch is DENIED at the dispatch event', () => {
  const out = hookOutput(payload(`Keel: implement this.\n\n${generatedOrder()}`));
  assert.ok(out, 'an unready order must not pass the dispatch event silently');
  assert.equal(out.hookSpecificOutput.hookEventName, L_HOOK_EVENT);
  assert.equal(out.hookSpecificOutput.permissionDecision, L_DENY);
  assert.match(out.hookSpecificOutput.permissionDecisionReason, /NOT READY/);
  assert.match(out.hookSpecificOutput.permissionDecisionReason, /AUTHOR REQUIRED/);
});

test('a READY order pasted into the dispatch is allowed through untouched', () => {
  assert.equal(hookOutput(payload(`Keel: implement this.\n\n${authoredOrder()}`)), null);
});

test('a dispatch that is Work-Order-shaped but carries no generated order is DENIED', () => {
  const freeform = [
    'WORK ORDER — make the thing work',
    'governance_head: 8bc5340',
    'private_surface: none',
    'credential_scope: none',
    'live_authority: none',
    'Commit onto build-020/whatever.',
  ].join('\n');
  const out = hookOutput(payload(freeform));
  assert.ok(out, 'the free-form bypass is the failure item 8 exists to close');
  assert.equal(out.hookSpecificOutput.permissionDecision, L_DENY);
  assert.match(out.hookSpecificOutput.permissionDecisionReason, /carries no GENERATED Work Order/);
});

test('an ordinary non-Work-Order dispatch is NOT touched — the gate must not brick the estate', () => {
  const veritas = [
    'Veritas: Gate 1 on the ACTIVE SESSION WORK PACKAGE in',
    'Deliverables/2026-08-04-build-015-asdair-wayfinder-plan.md.',
    'governance head 8bc5340. Return a separate PASS/HOLD/FAIL per numbered functional',
    'requirement. Do not narrow the audit to an older product slice.',
  ].join('\n');
  const pax = 'Pax: research dispatch-time validation in comparable estates. governance head 8bc5340.';
  assert.equal(hookOutput(payload(veritas)), null, 'an assurance dispatch must pass');
  assert.equal(hookOutput(payload(pax)), null, 'a research dispatch must pass');
});

test('naming the governance head alone never makes a dispatch look like a Work Order', () => {
  const shape = G.looksLikeWorkOrder(`please review this at ${L_NOT_A_SHAPE_SIGNAL} 8bc5340 and report`);
  assert.equal(shape.shaped, false, 'every dispatch in this estate names the governance head');
  assert.equal(G.ENVELOPE_FIELD_TOKENS.includes(L_NOT_A_SHAPE_SIGNAL), false);
});

test('a non-dispatch tool is never guarded', () => {
  assert.equal(hookOutput(payload('anything at all', { tool: 'Bash' })), null);
  assert.deepEqual(G.DISPATCH_TOOLS, [L_DISPATCH_TOOL]);
});

// ===========================================================================
// Referencing an order by path — the ordinary dispatch shape.
// ===========================================================================

// The ordinary dispatch shape is "your order is <path>". These two use REAL banked orders
// from this repository rather than fixtures, so the by-path route is proven against the
// corpus the CAPA was written about.
const L_UNREADY_BANKED_ORDER = 'Deliverables/proofline/WO-2026-08-06-ac5-3-mack-machine.md';
const L_READY_BANKED_ORDER = 'Deliverables/2026-08-09-WO-B15-C4-browser-contract-executable.md';

test('an UNREADY order referenced BY PATH is read and DENIED, not taken on trust', () => {
  const text = readFileSync(join(REPO, L_UNREADY_BANKED_ORDER), 'utf8');
  assert.equal(E.assessOrder(text, { root: REPO }).ready, false, 'precondition: this banked order is unready');
  const out = hookOutput(payload(`Keel: your order is ${L_UNREADY_BANKED_ORDER} — read it in full.`));
  assert.ok(out, 'an order named by path must be opened and assessed');
  assert.equal(out.hookSpecificOutput.permissionDecision, L_DENY);
  assert.match(out.hookSpecificOutput.permissionDecisionReason, new RegExp(L_UNREADY_BANKED_ORDER.replace(/[/.]/g, '\\$&')));
});

test('a READY order referenced BY PATH passes the dispatch event untouched', () => {
  const text = readFileSync(join(REPO, L_READY_BANKED_ORDER), 'utf8');
  assert.equal(E.assessOrder(text, { root: REPO }).ready, true, 'precondition: this banked order is ready');
  assert.equal(hookOutput(payload(`Keel: your order is ${L_READY_BANKED_ORDER} — read it in full.`)), null);
});

test('a cited document that is NOT an order is ignored — only the provenance marker counts', () => {
  const orders = G.collectOrders(
    'context: Deliverables/2026-08-04-proofline-wayfinder-plan.md and CLAUDE.md',
    [REPO],
  );
  assert.equal(orders.length, 0, 'a Wayfinder map is not a Work Order');
  assert.ok(!readFileSync(join(REPO, 'CLAUDE.md'), 'utf8').includes(L_ORDER_MARKER));
});

test('markdown references need a path separator — a bare filename is not a reference', () => {
  assert.deepEqual(G.markdownReferences('see notes.md and Deliverables/x.md'), ['Deliverables/x.md']);
});

// ===========================================================================
// Fail direction.
// ===========================================================================

test('unreadable input DEFERS rather than bricking every dispatch', () => {
  assert.equal(hookOutput(''), null);
  assert.equal(hookOutput('{not json'), null);
  assert.equal(hookOutput('[]'), null);
});

test('the guard emits ONLY on deny — a permitted dispatch produces no output at all', () => {
  assert.equal(G.toHookOutput({ decision: G.DECISION.DEFER, reason: 'fine' }), null);
  assert.equal(G.toHookOutput(null), null);
  const denied = G.toHookOutput({ decision: G.DECISION.DENY, reason: 'because' });
  assert.equal(denied.hookSpecificOutput.permissionDecision, L_DENY);
});

// ===========================================================================
// MUTATION PROOFS. Each asserts (a) the mutant genuinely stops refusing, and
// (b) the invariant that holds on the real module goes RED against the mutant.
// ===========================================================================

test('MUT-D1 the dispatch tool list emptied — nothing is guarded at all', async () => {
  const mutant = await loadMutant(
    "export const DISPATCH_TOOLS = ['Task'];",
    'export const DISPATCH_TOOLS = [];',
  );
  const raw = payload(`Keel: implement this.\n\n${generatedOrder()}`);
  assert.equal(mutant.toHookOutput(mutant.runHook(raw)), null, 'mutant should guard nothing');
  await assertMutantBreaks(
    mutant,
    (m) => assert.ok(m.toHookOutput(m.runHook(raw)), 'an unready order must be denied'),
    'MUT-D1 the subagent dispatch tool must be guarded',
  );
});

test('MUT-D2 the readiness verdict ignored — an unready order reaches the worker', async () => {
  const mutant = await loadMutant(
    '    const unready = assessed.filter((a) => !a.assessment.ready);',
    '    const unready = [];',
  );
  const raw = payload(`Keel: implement this.\n\n${generatedOrder()}`);
  assert.equal(mutant.toHookOutput(mutant.runHook(raw)), null, 'mutant should let the unready order through');
  await assertMutantBreaks(
    mutant,
    (m) => assert.ok(m.toHookOutput(m.runHook(raw))),
    'MUT-D2 an order the validator calls NOT READY must be denied at dispatch',
  );
});

test('MUT-D3 the free-form bypass reopened — a Work Order sent as prose is allowed', async () => {
  const mutant = await loadMutant(
    '  if (ORDER_PHRASE.test(String(text ?? \'\')) && fields.length >= 1) return { shaped: true, fields };',
    '  if (false) return { shaped: true, fields };',
  );
  const freeform = 'WORK ORDER — do the thing.\nprivate_surface: none\ngovernance_head: 8bc5340';
  const raw = payload(freeform);
  assert.equal(mutant.toHookOutput(mutant.runHook(raw)), null, 'mutant should reopen the bypass');
  await assertMutantBreaks(
    mutant,
    (m) => assert.ok(m.toHookOutput(m.runHook(raw))),
    'MUT-D3 sending a worker directly must not bypass the validator',
  );
});

test('MUT-D4 the provenance marker dropped from order detection — any cited doc becomes an order', async () => {
  const mutant = await loadMutant(
    '    if (!String(content).includes(ORDER_MARKER)) continue;',
    '    if (false) continue;',
  );
  const raw = payload('Veritas: review Deliverables/2026-08-04-proofline-wayfinder-plan.md at governance head 8bc5340.');
  const out = mutant.toHookOutput(mutant.runHook(raw));
  assert.ok(out, 'mutant should mistake a Wayfinder map for a Work Order and deny the assurance dispatch');
  await assertMutantBreaks(
    mutant,
    (m) => assert.equal(m.toHookOutput(m.runHook(raw)), null),
    'MUT-D4 only a document carrying the generator marker is a Work Order',
  );
});

test('MUT-D5 the deny output suppressed — the decision is made and never delivered', async () => {
  const mutant = await loadMutant(
    '  const permissionDecision = HOOK_DECISION[result.decision];',
    '  const permissionDecision = undefined;',
  );
  const raw = payload(`Keel: implement this.\n\n${generatedOrder()}`);
  assert.equal(
    mutant.runHook(raw).decision,
    G.DECISION.DENY,
    'mutant still DECIDES to deny — it simply stops telling the host',
  );
  assert.equal(mutant.toHookOutput(mutant.runHook(raw)), null, 'mutant should swallow the refusal');
  await assertMutantBreaks(
    mutant,
    (m) => assert.ok(m.toHookOutput(m.runHook(raw))),
    'MUT-D5 a refusal the host never receives is not a refusal',
  );
});

// ---------------------------------------------------------------------------
// AC4 — the two guarantees this order added, each broken ON PURPOSE.
// ---------------------------------------------------------------------------

test('MUT-D6 a decision path made to PROMPT WARWICK — both barriers removed', async () => {
  // The full breakout: the emission map is redirected to the prompting value AND the permitted
  // set is widened to admit it. Either alone is caught by the other, which is the point of
  // having two; this mutant removes both so a genuine prompt reaches the host.
  const mutant = await loadMutantAll([
    ["export const PERMITTED_HOOK_DECISIONS = Object.freeze(['deny']);", "export const PERMITTED_HOOK_DECISIONS = Object.freeze(['deny', 'ask']);"],
    ["export const HOOK_DECISION = Object.freeze({ [DECISION.DENY]: 'deny' });", "export const HOOK_DECISION = Object.freeze({ [DECISION.DENY]: 'ask' });"],
  ]);
  const raw = payload(`Keel: implement this.\n\n${generatedOrder()}`);
  const out = mutant.toHookOutput(mutant.runHook(raw));
  assert.ok(out, 'mutant must still emit');
  assert.equal(
    out.hookSpecificOutput.permissionDecision,
    L_PROMPTING_DECISION,
    'the mutant must genuinely put a prompt in front of Warwick, or this proves nothing',
  );
  await assertMutantBreaks(
    mutant,
    (m) => {
      const o = m.toHookOutput(m.runHook(raw));
      assert.notEqual(o?.hookSpecificOutput?.permissionDecision, L_PROMPTING_DECISION);
      assert.deepEqual(m.PERMITTED_HOOK_DECISIONS, L_PERMITTED_HOOK_DECISIONS);
    },
    'MUT-D6 no dispatch decision may ever ask Warwick to click',
  );
});

test('MUT-D6b ONE barrier removed — the second still refuses to prompt', async () => {
  // Defence in depth, proven rather than asserted: redirect the emission map alone and the
  // permitted-set check swallows it. A missed refusal, never a prompt. That is the chosen
  // fail direction stated in the module header, executed.
  const mutant = await loadMutant(
    "export const HOOK_DECISION = Object.freeze({ [DECISION.DENY]: 'deny' });",
    "export const HOOK_DECISION = Object.freeze({ [DECISION.DENY]: 'ask' });",
  );
  const raw = payload(`Keel: implement this.\n\n${generatedOrder()}`);
  assert.equal(mutant.toHookOutput(mutant.runHook(raw)), null, 'the permitted-set check must swallow an unpermitted value');
  await assertMutantBreaks(
    mutant,
    (m) => assert.ok(m.toHookOutput(m.runHook(raw)), 'an unready order must be denied'),
    'MUT-D6b breaking the emission map costs a refusal — it must never cost a prompt',
  );
});

test('MUT-D7 the refusal message stripped of its diagnostic — an opaque dead end', async () => {
  const mutant = await loadMutant(
    '    lines.push(renderAssessment(a.assessment, a.source));',
    "    lines.push('order not ready');",
  );
  const raw = payload(`Keel: implement this.\n\n${generatedOrder()}`);
  const reason = (m) => m.toHookOutput(m.runHook(raw)).hookSpecificOutput.permissionDecisionReason;
  assert.match(reason(G), /AUTHOR REQUIRED/, 'the real guard must name what is wrong with the order');
  assert.equal(/AUTHOR REQUIRED/.test(reason(mutant)), false, 'mutant should stop saying what is wrong');
  await assertMutantBreaks(
    mutant,
    (m) => assert.match(reason(m), /AUTHOR REQUIRED/),
    'MUT-D7 a refusal that does not name the offending field is the dead end Warwick forbade',
  );
});

// ===========================================================================
// AC2 at the dispatch event — the refusal Larry actually reads.
// ===========================================================================

test('a denied dispatch names the ABSENT and MALFORMED fields, never a bare "not ready"', () => {
  const broken = authoredOrder()
    .replace(/^private_surface: .*$/m, '')
    .replace(/^document_impact: \[\]$/m, 'document_impact: services/x/README.md (owner: keel) · Deliverables/y.md (owner: larry)');
  const out = hookOutput(payload(`Keel: implement this.\n\n${broken}`));
  assert.ok(out, 'an order with an absent and a malformed field must be denied');
  const reason = out.hookSpecificOutput.permissionDecisionReason;
  assert.equal(out.hookSpecificOutput.permissionDecision, L_DENY);
  assert.match(reason, /ABSENT[^;]*private_surface/, 'the absent field must be named, and labelled ABSENT');
  assert.match(reason, /MALFORMED/, 'the shape defect must be labelled MALFORMED, not merged with absence');
  assert.match(reason, /document_impact \(expected list, found scalar\)/, 'and it must say what was expected and what was found');
  assert.match(reason, /node tools\/wo\/envelope\.mjs --assess/, 'the refusal must say how to re-check the fix');
});

test('the free-form refusal names the envelope fields that made it look like an order', () => {
  const out = hookOutput(payload('WORK ORDER — do it.\nprivate_surface: none\ncredential_scope: none'));
  const reason = out.hookSpecificOutput.permissionDecisionReason;
  assert.match(reason, /private_surface/);
  assert.match(reason, /credential_scope/);
  assert.match(reason, /remove the envelope field names from the prompt/, 'a false positive must carry its own escape route');
});
