-- =====================================================================
-- IDEA-012 AsdAIr - WP1 database layer
-- Migration 001: asdair schema + tables
--
-- Purpose: replace per-run markdown reads with a queryable Postgres
--          schema for the weekly Asda household shopping agent.
--
-- Rules of the road:
--   * PURE ASCII only. No currency symbols, no smart quotes.
--   * NO secrets in SQL. asdair.credentials_ref is an AUDIT POINTER
--     only: it names the env var and where the value lives, never the
--     value itself.
--   * Idempotent: schema + tables use IF NOT EXISTS. The seed
--     (002_asdair_seed.sql) upserts on primary key.
--   * RLS is intentionally OUT OF SCOPE for WP1. Follow-up: add
--     row-level security once multi-user access is required
--     (see FOLLOW-UP note at the foot of this file).
-- =====================================================================

create schema if not exists asdair;

-- ---------------------------------------------------------------------
-- households / profiles
-- Separates one household's shop, another household's shop, and future profiles so that
-- lists, orders, rules, and products can all be scoped to one profile.
-- ---------------------------------------------------------------------
create table if not exists asdair.households (
    id           bigint generated by default as identity primary key,
    name         text not null unique,          -- stable key, e.g. 'household-a'
    display_name text,
    notes        text,
    created_at   timestamptz not null default now()
);

-- ---------------------------------------------------------------------
-- source_documents (migration provenance)
-- Every seeded rule / product / QA / order traces back to a Drive doc.
-- drive_file_id is a nullable pointer; the human-readable title is the
-- key we actually match on during migration.
-- ---------------------------------------------------------------------
create table if not exists asdair.source_documents (
    id            bigint generated by default as identity primary key,
    title         text not null unique,
    drive_file_id text,                          -- placeholder / pointer, not required
    doc_type      text not null,                 -- agent_spec | readme | decisions_log | order_history | shopping_list
    notes         text,
    created_at    timestamptz not null default now()
);

-- ---------------------------------------------------------------------
-- budget_settings
-- Per-household budget band for a "normal" shop (excludes delivery).
-- household_id NULL = global default band.
-- ---------------------------------------------------------------------
create table if not exists asdair.budget_settings (
    id           bigint generated by default as identity primary key,
    household_id bigint unique references asdair.households(id),
    min_normal   numeric(10,2) not null default 120,
    max_normal   numeric(10,2) not null default 150,
    currency     text not null default 'GBP',
    created_at   timestamptz not null default now(),
    -- PR #36 Fable finding #7: guard against an inverted budget band. The
    -- "normal" shop range must be non-empty, i.e. the floor cannot exceed the
    -- ceiling. loadBudget() and the planner's within/over/under band logic both
    -- assume min_normal <= max_normal.
    check (min_normal <= max_normal)
);

-- Gap closed: the inline `household_id unique` keeps ONE row per non-null
-- household, but a plain UNIQUE treats NULLs as distinct, so it allowed
-- UNLIMITED global (household_id IS NULL) rows. loadBudget() reads the global
-- band with `WHERE household_id IS NULL LIMIT 1`; two globals = silent
-- ambiguity. This partial unique index indexes the constant expression
-- (household_id IS NULL) over only the global rows, so at most ONE can exist.
create unique index if not exists uq_budget_one_global
    on asdair.budget_settings ((household_id is null))
    where household_id is null;

-- ---------------------------------------------------------------------
-- credentials_ref  (AUDIT POINTER ONLY - NEVER A SECRET VALUE)
-- Names the env var and describes where the real value is stored.
-- The value itself never lives in this table or anywhere in SQL.
-- ---------------------------------------------------------------------
create table if not exists asdair.credentials_ref (
    id                    bigint generated by default as identity primary key,
    env_var_name          text not null unique,
    storage_location_note text not null,         -- e.g. 'server .env, managed outside DB'
    last_rotated          date,
    created_at            timestamptz not null default now()
);

-- ---------------------------------------------------------------------
-- rules
-- Standing behavioural + product rules for the agent.
--   scope    : granularity the rule matches
--              global | household | category | product | one_time
--   active   : superseded rules are set active=false (kept for audit)
--   directive: structured action the planner takes (see comment below)
--   household_id     : whose preference (NULL = applies to all)
--   superseded_by    : self-FK to the rule that replaced this one
--   source_document_id : provenance
-- ---------------------------------------------------------------------
create table if not exists asdair.rules (
    id                 bigint generated by default as identity primary key,
    category           text not null,
    rule_text          text not null,
    scope              text not null default 'global'
                         check (scope in ('global','household','category','product','one_time')),
    active             boolean not null default true,
    -- STRUCTURED directive fields the planner acts on (map / needs_decision /
    -- exclude). A row with directive='info' (the default) is purely
    -- INFORMATIONAL: the pure planner ignores its free-text rule_text and it
    -- never changes a basket. match_term / match_category say what the rule
    -- targets; matched_product is the replacement for a 'map' directive; reason
    -- and note are surfaced to a human. IMPORTANT: the actual directive VALUES
    -- (which rule maps or excludes what) are household PREFERENCE DATA that live
    -- ONLY in the private Supabase asdair schema and are NEVER committed to git
    -- -- the same boundary as the gitignored seed (002_asdair_seed.sql). This
    -- migration ships the columns (structure), never the rows (data).
    directive          text not null default 'info'
                         check (directive in ('info','exclude','needs_decision','map')),
    match_term         text,
    match_category     text,
    matched_product    text,
    reason             text,
    note               text,
    household_id       bigint references asdair.households(id),
    superseded_by      bigint references asdair.rules(id),
    source_document_id bigint references asdair.source_documents(id),
    created_at         timestamptz not null default now(),
    -- PR #36 Fable finding #6 (schema-side defence): an ACTIONABLE directive
    -- (map / exclude / needs_decision) must name a target to act on -- either a
    -- match_term or a match_category. Only a purely INFORMATIONAL directive
    -- ('info') may be target-less. Without this, a target-less 'map'/'exclude'
    -- row would be a silent no-op the planner cannot apply. (Mack adds the
    -- matching planner-side guard separately.)
    -- PR #36 direct-Codex re-review: an EMPTY or whitespace-only target is NOT
    -- a real target. A plain `... is not null` accepted match_term = '' (empty
    -- string is not null), so an actionable directive with an effectively
    -- target-less '' / '   ' slipped through -- exactly the silent no-op this
    -- CHECK exists to stop. nullif(btrim(...), '') folds empty/whitespace-only
    -- back to NULL, so an actionable directive now REQUIRES a non-empty,
    -- non-whitespace match_term or match_category. This matches the planner's
    -- hasTarget, which already normalises empty -> no-target.
    check (directive = 'info' or nullif(btrim(match_term), '') is not null or nullif(btrim(match_category), '') is not null)
);

-- ---------------------------------------------------------------------
-- rule_qa_log
-- Dated decision-log entries. When a decision becomes a standing rule,
-- promoted_rule_id points at the resulting asdair.rules row.
-- ---------------------------------------------------------------------
create table if not exists asdair.rule_qa_log (
    id                    bigint generated by default as identity primary key,
    asked_on              date not null,
    question              text not null,
    answer                text not null,
    applies_going_forward boolean not null default false,
    promoted_rule_id      bigint references asdair.rules(id),
    household_id          bigint references asdair.households(id),
    source_document_id    bigint references asdair.source_documents(id),
    created_at            timestamptz not null default now()
);

-- ---------------------------------------------------------------------
-- products
-- list_term (as written on a list) -> matched_product (the exact Asda
-- product to select). Scoped to a household where the preference is
-- family-specific (NULL = global mapping).
-- ---------------------------------------------------------------------
create table if not exists asdair.products (
    id                 bigint generated by default as identity primary key,
    list_term          text not null,
    matched_product    text not null,
    category           text,
    notes              text,
    household_id       bigint references asdair.households(id),
    source_document_id bigint references asdair.source_documents(id),
    created_at         timestamptz not null default now()
);

-- Gap closed: the old inline `unique (household_id, list_term)` was both (a)
-- NULL-permissive -- it allowed MANY global rows for the same term because
-- NULL household_id compares distinct -- and (b) NOT normalised, so 'Widget A'
-- and '  widget   a ' were treated as different terms even though the planner
-- (normaliseTerm: lower-case, trim, collapse internal whitespace) treats them
-- as identical. These two PARTIAL unique indexes normalise the term to match
-- normaliseTerm exactly and enforce uniqueness within each scope separately:
--   * global rows (household_id IS NULL): at most one mapping per normalised
--     term across the whole install.
--   * household rows (household_id IS NOT NULL): at most one mapping per term
--     per household.
-- A GLOBAL default and a HOUSEHOLD-specific override for the SAME term remain
-- allowed, because they land in different partial indexes (different WHERE).
-- NORMALISATION ORDER MATTERS (PR #36 Fable finding #2): collapse whitespace
-- FIRST, then btrim. Postgres btrim(text) strips SPACES only, so running it
-- BEFORE the collapse left a leading TAB/newline intact -- e.g. E'\twidget a'
-- btrim'd to E'\twidget a', then collapsed to ' widget a' (leading space),
-- which did NOT collide with 'widget a'. The planner's normaliseTerm
-- (trim -> lower -> collapse) treats both as 'widget a', so the index under-
-- enforced. Reordering to regexp_replace(collapse) -> btrim -> lower makes the
-- index match normaliseTerm for ASCII whitespace.
-- RESIDUAL DIVERGENCE (out of scope to fully unify here): JS `\s` matches the
-- full Unicode space set, whereas Postgres `\s` / `[[:space:]]` cover only the
-- ASCII/C-locale whitespace class, so exotic Unicode spaces could still differ.
create unique index if not exists uq_products_global_term
    on asdair.products ((lower(btrim(regexp_replace(list_term, '\s+', ' ', 'g')))))
    where household_id is null;

create unique index if not exists uq_products_household_term
    on asdair.products (household_id, (lower(btrim(regexp_replace(list_term, '\s+', ' ', 'g')))))
    where household_id is not null;

-- ---------------------------------------------------------------------
-- shopping_lists
-- One weekly list per household. list_date is unique per household.
--   transcription_confidence : 0.000-1.000 (NULL when unknown)
--   needs_review             : flag low-confidence transcriptions
-- ---------------------------------------------------------------------
create table if not exists asdair.shopping_lists (
    id                       bigint generated by default as identity primary key,
    household_id             bigint not null references asdair.households(id),
    list_date                date not null,
    telegram_file_id         text,
    raw_transcription        text,
    transcription_confidence numeric(4,3),
    needs_review             boolean not null default false,
    status                   text not null default 'pending',  -- pending | processed | archived
    source_document_id       bigint references asdair.source_documents(id),
    created_at               timestamptz not null default now(),
    unique (household_id, list_date)
);

-- ---------------------------------------------------------------------
-- shopping_list_items
-- One row per line on a list.
--   requested_qty  : item count as interpreted from the list
--   added_qty      : count actually placed in basket by the agent
--   one_week_only  : per-week note/exclusion that does NOT become a rule
--   status         : requested | added | needs_decision | not_added
--                    | excluded_this_week
-- ---------------------------------------------------------------------
create table if not exists asdair.shopping_list_items (
    id                bigint generated by default as identity primary key,
    list_id           bigint not null references asdair.shopping_lists(id),
    item_name         text not null,
    matched_product_id bigint references asdair.products(id),
    requested_qty     integer not null default 1,
    added_qty         integer,
    status            text not null default 'requested',
    price             numeric(10,2),
    note              text,
    one_week_only     boolean not null default false,
    created_at        timestamptz not null default now()
);

-- ---------------------------------------------------------------------
-- product_alternatives
-- Alternatives offered when a list item is out of stock / ambiguous.
-- The agent NEVER auto-substitutes; alternatives await a human choice.
-- ---------------------------------------------------------------------
create table if not exists asdair.product_alternatives (
    id               bigint generated by default as identity primary key,
    list_item_id     bigint not null references asdair.shopping_list_items(id),
    alternative_name text not null,
    price            numeric(10,2),
    chosen           boolean not null default false,
    created_at       timestamptz not null default now()
);

-- ---------------------------------------------------------------------
-- orders
-- One agent run against a shopping_list. The goal is a checkout-ready
-- basket; the agent NEVER places the order (checked_out stays false).
--   attempt : run-attempt counter for retried / failed browser runs
-- ---------------------------------------------------------------------
create table if not exists asdair.orders (
    id                   bigint generated by default as identity primary key,
    list_id              bigint not null references asdair.shopping_lists(id),
    household_id         bigint not null references asdair.households(id),
    run_at               timestamptz,
    total_requested      integer,
    total_added          integer,
    total_needs_decision integer,
    basket_total         numeric(10,2),
    outside_budget_range boolean not null default false,
    checked_out          boolean not null default false,
    checked_out_at       timestamptz,
    attempt              integer not null default 1,
    source_document_id   bigint references asdair.source_documents(id),
    created_at           timestamptz not null default now()
);

-- ---------------------------------------------------------------------
-- order_events
-- Timeline of what happened during a run: corrections, flags, info,
-- decisions needed, errors.
-- ---------------------------------------------------------------------
create table if not exists asdair.order_events (
    id          bigint generated by default as identity primary key,
    order_id    bigint not null references asdair.orders(id),
    event_type  text not null
                  check (event_type in ('correction','flag','info','decision','error','warning')),
    description text not null,
    occurred_at timestamptz not null default now(),
    created_at  timestamptz not null default now()
);

-- ---------------------------------------------------------------------
-- process_suggestions
-- Agent-proposed process improvements arising from a run, awaiting a
-- human decision. (No seed rows in WP1; table is ready for use.)
-- ---------------------------------------------------------------------
create table if not exists asdair.process_suggestions (
    id         bigint generated by default as identity primary key,
    order_id   bigint not null references asdair.orders(id),
    suggestion text not null,
    status     text not null default 'proposed',  -- proposed | accepted | rejected
    decided_at timestamptz,
    created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------
-- Helpful indexes for the read-only skill's common lookups.
-- ---------------------------------------------------------------------
create index if not exists idx_rules_active            on asdair.rules (active);
create index if not exists idx_rules_scope             on asdair.rules (scope);
create index if not exists idx_rules_household         on asdair.rules (household_id);
create index if not exists idx_products_household      on asdair.products (household_id);
create index if not exists idx_lists_household         on asdair.shopping_lists (household_id);
create index if not exists idx_list_items_list         on asdair.shopping_list_items (list_id);
create index if not exists idx_list_items_status       on asdair.shopping_list_items (status);
create index if not exists idx_alternatives_list_item  on asdair.product_alternatives (list_item_id);
create index if not exists idx_orders_list             on asdair.orders (list_id);
create index if not exists idx_orders_household        on asdair.orders (household_id);
create index if not exists idx_order_events_order      on asdair.order_events (order_id);
create index if not exists idx_suggestions_order       on asdair.process_suggestions (order_id);

-- =====================================================================
-- FOLLOW-UP (out of scope for WP1):
--   * Row-Level Security (RLS): once more than one human/profile reads
--     or writes this schema, enable RLS and add per-household policies
--     on shopping_lists, shopping_list_items, orders, order_events,
--     product_alternatives, process_suggestions, and household-scoped
--     rules/products. WP1 deliberately ships without RLS to keep the
--     first migration + read-only skill simple.
--   * Consider an ENUM type for status/event_type once the value sets
--     stabilise (kept as CHECK-constrained text for now).
-- =====================================================================
