-- =====================================================================
-- IDEA-012 AsdAIr - migration 004: asdair.regulars
--
-- Purpose: commit the STRUCTURE of the household "regulars" table -- the
--          standing list of items a household buys week after week, which
--          the weekly shop is built from.
--
-- WHY THIS FILE EXISTS:
--   asdair.regulars is LIVE and load-bearing, but it had NO committed
--   migration: it existed only in the live database. A clean database built
--   from git alone (001 + this file) therefore could not be stood up, and
--   nothing in review could see the shape the code depends on. This
--   migration reproduces the live table faithfully so git is again the
--   source of truth for the schema.
--
-- Rules of the road (same as 001_asdair_schema.sql):
--   * PURE ASCII only. No currency symbols, no smart quotes.
--   * NO secrets, and NO ROWS. The household's actual regulars are personal
--     preference data that live ONLY in the private Supabase asdair schema
--     and are NEVER committed to git -- the same boundary as the gitignored
--     seed (002_asdair_seed.sql). This migration ships COLUMNS (structure),
--     never rows (data).
--   * Idempotent: create table / index IF NOT EXISTS, so re-running it
--     against a database that already has the live table is a no-op and
--     never rewrites or drops anything.
--   * Depends on 001_asdair_schema.sql (the asdair schema and
--     asdair.households must exist first).
-- =====================================================================

-- ---------------------------------------------------------------------
-- regulars
-- One row per item this household normally buys.
--   household_id        : whose regulars these are (defaults to household 1,
--                         matching live; the FK keeps it a real household)
--   high_level_category : coarse grouping used when laying out a shop
--   category            : finer grouping, aligned with products.category
--   name                : the item as the household refers to it
--   asda_product_id     : the store's product identifier, when known
--   asda_url            : deep link to the product page, when known
--   typical_qty         : the count usually bought (item count, not pack size)
--   source              : where this regular came from, e.g. 'regular'
--   active              : retired regulars are set false, never deleted
--   brand               : preferred brand, when the household has one
--   aka                 : alternative names the same item is written as, so a
--                         list line can be recognised however it was phrased
--   substitutes_allowed : whether a substitute may be CONSIDERED for this
--                         item. It never authorises the agent to substitute
--                         on its own -- out-of-stock still goes to a human
--                         (rule 6); it only records the household's standing
--                         preference.
--
-- UNIQUE (household_id, source, name): one regular per name per source per
-- household, so re-importing a source cannot silently duplicate an item.
-- ---------------------------------------------------------------------
create table if not exists asdair.regulars (
    id                  bigint generated by default as identity primary key,
    household_id        bigint not null default 1 references asdair.households(id),
    high_level_category text,
    category            text,
    name                text not null,
    asda_product_id     text,
    asda_url            text,
    typical_qty         integer,
    source              text not null default 'regular',
    active              boolean not null default true,
    created_at          timestamptz not null default now(),
    updated_at          timestamptz not null default now(),
    brand               text,
    aka                 text[] not null default '{}'::text[],
    substitutes_allowed boolean not null default false,
    unique (household_id, source, name)
);

-- ---------------------------------------------------------------------
-- Indexes (names match live exactly).
--   *_household_category_idx : browsing / laying out a shop by category
--   *_household_brand_idx    : brand-preference lookups
--   *_aka_gin                : containment / overlap searches over the
--                              alternative-name array (gin, array_ops)
-- ---------------------------------------------------------------------
create index if not exists regulars_household_category_idx
    on asdair.regulars (household_id, category);

create index if not exists regulars_household_brand_idx
    on asdair.regulars (household_id, brand);

create index if not exists regulars_aka_gin
    on asdair.regulars using gin (aka);

-- =====================================================================
-- FOLLOW-UP (inherited from 001, out of scope here):
--   * Row-Level Security: asdair.regulars is household-scoped and belongs
--     in the same RLS pass as the other household-scoped tables once more
--     than one human/profile reads or writes this schema.
--   * updated_at is defaulted but not auto-maintained; a trigger (or the
--     writer setting it explicitly) is a separate decision, deliberately
--     NOT introduced by this structure-only migration.
-- =====================================================================
