-- =====================================================================
-- BUILD-015 AsdAIr Stage 1 - migration 006: the shop control surface
--
-- WHY: ShopperBot becomes the control surface for the whole supervised shop.
-- That needs durable state for things that until now lived in a session:
-- what arrived, what it said, what stage it is at, what is still unanswered,
-- what the browser runner has been asked to do, and what the order
-- confirmation said. Telegram is a VIEW over these tables - never the record.
--
-- DESIGN RULES
--   * A weekly shop is identified by a human-readable shop_ref (SHOP-YYYY-MM-DD)
--     so Warwick and the bot can refer to the same thing.
--   * Idempotency is structural, not conventional: the natural keys below make a
--     repeated Telegram delivery or a repeated button tap a no-op, because the
--     directive is explicit that neither may duplicate a list, a decision or an
--     order.
--   * Raw evidence (the photo, the pasted text, the confirmation) is ALWAYS
--     retained. It is what the shop was produced from.
--   * PURE ASCII. No secrets, no rows. Idempotent - safe to re-run.
--   * Depends on 001 (schema + households) and 004 (regulars).
-- =====================================================================

-- ---------------------------------------------------------------------
-- shop - one row per weekly shop, from arrival to reconciliation.
-- ---------------------------------------------------------------------
create table if not exists asdair.shop (
  id                    bigint generated by default as identity primary key,
  household_id          bigint not null references asdair.households(id),
  shop_ref              text   not null,
  status                text   not null default 'RECEIVED',

  -- provenance of the inbound request
  source_kind           text   not null,              -- 'text' | 'photo'
  telegram_chat_id      text,
  telegram_message_id   text,
  telegram_update_id    text,

  -- raw evidence, always retained
  raw_text              text,
  raw_media_path        text,

  -- transcription (photo lists only)
  transcript            text,
  transcript_provider   text,                          -- provenance, never credentials
  transcript_model      text,
  transcript_confidence numeric,
  needs_review          boolean not null default false,

  -- the real list, once created by the worker
  list_id               bigint references asdair.shopping_lists(id),

  last_error            text,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now(),

  constraint shop_status_known check (status in (
    'RECEIVED','TRANSCRIBING','PROCESSING','NEEDS_DECISION','READY_TO_SHOP',
    'WAITING_FOR_BROWSER','SHOPPING','BASKET_READY','ORDER_CONFIRMATION_RECEIVED',
    'RECONCILED','FAILED','CANCELLED')),
  constraint shop_source_known check (source_kind in ('text','photo'))
);

-- The shop_ref is the human handle and must be unique per household.
create unique index if not exists shop_ref_uniq on asdair.shop (household_id, shop_ref);

-- STRUCTURAL IDEMPOTENCY: one Telegram message can only ever create one shop,
-- so a redelivered update resumes rather than duplicating the week.
create unique index if not exists shop_inbound_uniq
  on asdair.shop (telegram_chat_id, telegram_message_id)
  where telegram_chat_id is not null and telegram_message_id is not null;

-- ---------------------------------------------------------------------
-- shop_event - the audit trail of stage transitions, failures and milestones.
-- ---------------------------------------------------------------------
create table if not exists asdair.shop_event (
  id          bigint generated by default as identity primary key,
  shop_id     bigint not null references asdair.shop(id) on delete cascade,
  event_type  text   not null,        -- 'transition' | 'milestone' | 'failure' | 'decision' | 'note'
  from_status text,
  to_status   text,
  description text   not null,
  occurred_at timestamptz not null default now()
);
create index if not exists shop_event_shop_idx on asdair.shop_event (shop_id, id);

-- ---------------------------------------------------------------------
-- shop_question - the Telegram question loop. One row per genuinely
-- unresolved item. question_key makes re-asking impossible on a re-run.
-- ---------------------------------------------------------------------
create table if not exists asdair.shop_question (
  id             bigint generated by default as identity primary key,
  shop_id        bigint not null references asdair.shop(id) on delete cascade,
  list_item_id   bigint references asdair.shopping_list_items(id),
  question_key   text   not null,
  question_text  text   not null,
  candidates     jsonb  not null default '[]'::jsonb,
  status         text   not null default 'open',   -- 'open' | 'answered' | 'skipped'
  answer_text    text,
  answer_source  text,                              -- 'button' | 'typed'
  card_chat_id   text,
  card_message_id text,
  asked_at       timestamptz not null default now(),
  answered_at    timestamptz,
  constraint shop_question_status_known check (status in ('open','answered','skipped'))
);
-- Ask each distinct question at most once per shop.
create unique index if not exists shop_question_key_uniq on asdair.shop_question (shop_id, question_key);
create index if not exists shop_question_open_idx on asdair.shop_question (shop_id, status);

-- ---------------------------------------------------------------------
-- browser_build_request - the durable "build the ASDA basket" request.
-- A supervised runner CLAIMS it; nothing autonomous ever does.
-- ---------------------------------------------------------------------
create table if not exists asdair.browser_build_request (
  id           bigint generated by default as identity primary key,
  shop_id      bigint not null references asdair.shop(id) on delete cascade,
  status       text   not null default 'queued',   -- queued|claimed|running|complete|failed|cancelled
  claimed_by   text,
  progress     jsonb  not null default '{}'::jsonb,
  last_error   text,
  requested_at timestamptz not null default now(),
  claimed_at   timestamptz,
  finished_at  timestamptz,
  constraint bbr_status_known check (status in ('queued','claimed','running','complete','failed','cancelled'))
);
-- At most ONE live request per shop, so repeated taps resume rather than queue again.
create unique index if not exists bbr_one_live_per_shop
  on asdair.browser_build_request (shop_id)
  where status in ('queued','claimed','running');

-- ---------------------------------------------------------------------
-- pending_action - browser-only maintenance that could not be completed
-- (e.g. "add Wall's to ASDA Favourites"). Surfaced in status, never forgotten.
-- ---------------------------------------------------------------------
create table if not exists asdair.pending_action (
  id           bigint generated by default as identity primary key,
  household_id bigint not null references asdair.households(id),
  shop_id      bigint references asdair.shop(id) on delete set null,
  action_type  text   not null,                    -- e.g. 'add_favourite'
  action_key   text   not null,
  payload      jsonb  not null default '{}'::jsonb,
  status       text   not null default 'pending',  -- pending|done|abandoned
  note         text,
  created_at   timestamptz not null default now(),
  resolved_at  timestamptz,
  constraint pending_action_status_known check (status in ('pending','done','abandoned'))
);
create unique index if not exists pending_action_key_uniq
  on asdair.pending_action (household_id, action_type, action_key)
  where status = 'pending';

-- ---------------------------------------------------------------------
-- order_confirmation - the raw ASDA confirmation plus its parse.
-- Raw is retained ALWAYS; parsed is derived and may be re-derived.
-- ---------------------------------------------------------------------
create table if not exists asdair.order_confirmation (
  id             bigint generated by default as identity primary key,
  shop_id        bigint not null references asdair.shop(id) on delete cascade,
  order_id       bigint references asdair.orders(id),
  source_kind    text   not null,                  -- 'text' | 'photo' | 'document'
  raw_text       text,
  raw_media_path text,
  parsed         jsonb  not null default '{}'::jsonb,
  parse_provider text,
  stated_total   numeric,                          -- only when EXPLICITLY shown
  received_at    timestamptz not null default now(),
  reconciled_at  timestamptz,
  constraint order_confirmation_source_known check (source_kind in ('text','photo','document'))
);
create index if not exists order_confirmation_shop_idx on asdair.order_confirmation (shop_id, id);

-- ---------------------------------------------------------------------
-- Line-level reconciliation. price_basis records HOW a price is known -
-- 'stated' (ASDA showed it) vs 'derived' (inferred). The directive is
-- explicit: an inferred price may NEVER be presented as an ASDA-quoted value.
-- ---------------------------------------------------------------------
create table if not exists asdair.order_confirmation_line (
  id                bigint generated by default as identity primary key,
  confirmation_id   bigint not null references asdair.order_confirmation(id) on delete cascade,
  line_no           integer not null,
  product_name      text   not null,
  quantity          integer,
  pack_size         text,
  promotion         text,
  line_price        numeric,
  price_basis       text   not null default 'stated',
  matched_regular_id bigint references asdair.regulars(id),
  outcome           text,   -- as_planned|added_after_planning|omitted|qty_changed|variant_changed|unmatched
  note              text,
  constraint occl_price_basis_known check (price_basis in ('stated','derived','unknown'))
);
create index if not exists occl_confirmation_idx on asdair.order_confirmation_line (confirmation_id, line_no);

-- ---------------------------------------------------------------------
-- Grants. Same safety posture as 005: the writer may create and progress a
-- shop, and may never delete one.
-- ---------------------------------------------------------------------
do $$
begin
  if not exists (select 1 from pg_roles where rolname = 'asdair_rw') then
    raise notice 'asdair_rw absent - skipping 006 grants';
    return;
  end if;

  execute 'grant select, insert, update on asdair.shop                    to asdair_rw';
  execute 'grant select, insert          on asdair.shop_event             to asdair_rw';
  execute 'grant select, insert, update on asdair.shop_question           to asdair_rw';
  execute 'grant select, insert, update on asdair.browser_build_request   to asdair_rw';
  execute 'grant select, insert, update on asdair.pending_action          to asdair_rw';
  execute 'grant select, insert, update on asdair.order_confirmation      to asdair_rw';
  execute 'grant select, insert, update on asdair.order_confirmation_line to asdair_rw';

  execute 'grant usage on sequence ' || pg_get_serial_sequence('asdair.shop',                    'id') || ' to asdair_rw';
  execute 'grant usage on sequence ' || pg_get_serial_sequence('asdair.shop_event',              'id') || ' to asdair_rw';
  execute 'grant usage on sequence ' || pg_get_serial_sequence('asdair.shop_question',           'id') || ' to asdair_rw';
  execute 'grant usage on sequence ' || pg_get_serial_sequence('asdair.browser_build_request',   'id') || ' to asdair_rw';
  execute 'grant usage on sequence ' || pg_get_serial_sequence('asdair.pending_action',          'id') || ' to asdair_rw';
  execute 'grant usage on sequence ' || pg_get_serial_sequence('asdair.order_confirmation',      'id') || ' to asdair_rw';
  execute 'grant usage on sequence ' || pg_get_serial_sequence('asdair.order_confirmation_line', 'id') || ' to asdair_rw';

  -- The read/planning role must see all of it.
  execute 'grant select on asdair.shop, asdair.shop_event, asdair.shop_question, '
       || 'asdair.browser_build_request, asdair.pending_action, '
       || 'asdair.order_confirmation, asdair.order_confirmation_line to asdair_ro';
end $$;
