-- =====================================================================
-- BUILD-015 AsdAIr Stage 1 - migration 008: asdair.shop_line
--
-- WHY: the catalogue-grounded interpreter (services/asdair/interpret/) and the
-- deterministic identity resolver were built and proven, but their OUTPUT had
-- nowhere durable to live. The cockpit reader had to probe information_schema
-- for columns that did not exist. That is the same defect as the 'rotate'
-- directive before migration 007: the mechanism was live and unreachable.
--
-- This table is the durable home for the interpreted list - the thing the
-- Cockpit shows, the human corrects and confirms, and the planner builds from.
--
-- THE INVARIANT IT ENCODES (see services/asdair/interpret/README.md):
--   the model READS and RANKS      -> raw_reading, confidence, alternatives
--   the catalogue DETERMINES IDENTITY -> matched_regular_id, a real FK
--   the human RESOLVES ambiguity   -> confirmed_by / confirmed_at / status
--
-- matched_regular_id is a genuine FOREIGN KEY to asdair.regulars. A model
-- cannot therefore invent a product that does not exist: an id that names no
-- row is rejected by the database, not merely by code. The canonical product
-- name is NOT stored here - it is looked up from regulars by id, so a rename
-- can never leave a stale name on a shopping list.
--
-- PURE ASCII, no secrets, no rows, idempotent. Depends on 006 (shop) and 004.
-- =====================================================================

create table if not exists asdair.shop_line (
  id                 bigint generated by default as identity primary key,
  shop_id            bigint  not null references asdair.shop(id) on delete cascade,
  line_no            integer not null,

  -- What the model believes is physically on the paper. Kept VERBATIM: it is
  -- the evidence for every later decision, and the only field of model prose.
  raw_reading        text    not null,
  quantity           integer,                       -- null = not visibly written, or unreadable

  -- Identity, decided by the catalogue.
  matched_regular_id bigint  references asdair.regulars(id),
  match_basis        text,
  match_confidence   numeric,
  alternatives       jsonb   not null default '[]'::jsonb,

  status             text    not null default 'needs_confirmation',

  -- Human confirmation / correction.
  confirmed_by       text,
  confirmed_at       timestamptz,
  corrected          boolean not null default false,

  -- Set once the confirmed line becomes a real list item.
  list_item_id       bigint  references asdair.shopping_list_items(id),

  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now(),

  constraint shop_line_status_known check (status in (
    'matched','needs_confirmation','unmatched_new_item','unreadable','possible_duplicate','excluded')),

  -- A 'matched' line MUST carry a real regular id. This is the grounding
  -- invariant enforced by the database rather than by convention: nothing can
  -- record a confident match to nothing.
  constraint shop_line_matched_has_id check (status <> 'matched' or matched_regular_id is not null),

  -- Quantity, when present, must be sane. Never guessed - null is a first-class
  -- value meaning "ask a human".
  constraint shop_line_qty_sane check (quantity is null or (quantity > 0 and quantity <= 999))
);

-- One row per line per shop: re-running interpretation UPDATES a line rather
-- than appending a second copy of the same list.
create unique index if not exists shop_line_shop_lineno_uniq on asdair.shop_line (shop_id, line_no);
create index if not exists shop_line_shop_status_idx on asdair.shop_line (shop_id, status);

do $$
begin
  if not exists (select 1 from pg_roles where rolname = 'asdair_rw') then return; end if;
  execute 'grant select, insert, update on asdair.shop_line to asdair_rw';
  execute 'grant usage on sequence ' || pg_get_serial_sequence('asdair.shop_line','id') || ' to asdair_rw';
  execute 'grant select on asdair.shop_line to asdair_ro';
end $$;
