-- =====================================================================
-- BUILD-015 AsdAIr Stage 1 - migration 009
--
-- TWO CORRECTIONS, both of which were "working" while quietly wrong.
--
-- (1) SEPARATE THE MACHINE LEDGER FROM HUMAN ACTIONS.
--     The pipeline kept its command/resume bookkeeping in
--     asdair.pending_action, namespaced 'cmd:' / 'msg:'. That table is what
--     Cockpit and Telegram surface to Warwick as OUTSTANDING ACTIONS - so
--     internal plumbing would appear as things he has to do. Two different
--     concepts shared one home. Filtering it in the UI would have hidden the
--     symptom and left the confusion in the data, so they now have two homes.
--
--       asdair.pipeline_command  -> machine command / outbox / resume ledger
--       asdair.pending_action    -> genuine human actions only (e.g. "add
--                                   Wall's to ASDA Favourites")
--
-- (2) THE QUESTION RENDER CONTRACT.
--     A Telegram button carries a candidate INDEX, not a product id (that is
--     what keeps callback_data inside its 64-byte budget). An index is only
--     meaningful against the exact list that was DISPLAYED. Without recording
--     that list, a re-render that reordered candidates would silently
--     reinterpret an old button as a DIFFERENT PRODUCT - and the shopper would
--     never know. rendered_candidates + render_fingerprint make a stale tap
--     detectable and therefore refusable.
--
-- PURE ASCII, no secrets, no rows, idempotent. Depends on 006.
-- =====================================================================

create table if not exists asdair.pipeline_command (
  id              bigint generated by default as identity primary key,
  shop_id         bigint references asdair.shop(id) on delete cascade,
  kind            text not null default 'command',   -- 'command' | 'outbox'
  command         text not null,
  args            jsonb not null default '{}'::jsonb,
  idempotency_key text not null,
  status          text not null default 'pending',   -- pending|running|done|failed|retired
  attempts        integer not null default 0,
  last_error      text,
  result          jsonb,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  constraint pipeline_command_kind_known check (kind in ('command','outbox')),
  constraint pipeline_command_status_known check (status in ('pending','running','done','failed','retired'))
);

-- THE idempotency guarantee: a repeated button tap or a Telegram redelivery
-- resolves to the SAME row instead of queueing another unit of work.
create unique index if not exists pipeline_command_idem_uniq on asdair.pipeline_command (idempotency_key);
create index if not exists pipeline_command_open_idx on asdair.pipeline_command (status, shop_id);

-- The render contract for question cards.
alter table asdair.shop_question add column if not exists rendered_candidates jsonb not null default '[]'::jsonb;
alter table asdair.shop_question add column if not exists render_fingerprint  text;
alter table asdair.shop_question add column if not exists render_version      integer not null default 1;
alter table asdair.shop_question add column if not exists callback_index      integer;

do $$
begin
  if not exists (select 1 from pg_roles where rolname = 'asdair_rw') then return; end if;
  execute 'grant select, insert, update on asdair.pipeline_command to asdair_rw';
  execute 'grant usage on sequence ' || pg_get_serial_sequence('asdair.pipeline_command','id') || ' to asdair_rw';
  execute 'grant select on asdair.pipeline_command to asdair_ro';
end $$;
