-- =============================================================================
-- MyPKA cockpit seed — BUILD-002 Unified Fusion Hub contract, v0.1-draft (DRAFT state)
--
-- Populates cockpit.build_contract as the OPERATIONAL DRAFT record + readable Directus projection
-- of the canonical Git contract. GitHub Markdown stays canonical; this is a projection + the
-- approved-version binding target.
--
-- Bound to the committed contract:
--   path        Builds/BUILD-002-unified-personal-capture-gateway/BUILD-CONTRACT.md
--   commit      96ed15d30c83904d1e615e47e57b54dc5fbe0861
--   git blob    3e6661efd511d0dd2e87c217062b1cdd66540b94
--   sha256      83e1b41a693ea0c7f9a86a79d43db988f937df704f14e82e7a8b4c8203f9cf2c   (over the committed blob)
--
-- Idempotent: on conflict refreshes the READABLE PROJECTION only — never lifecycle_state /
-- approved_by / approved_at (re-seeding can never reset an approval). Reversible via teardown.sql.
-- =============================================================================
insert into cockpit.build_contract (
  build_id, contract_version, doc_type, title, outcome, executive_summary,
  scope, non_goals, objectives, wp_sequence, acceptance_criteria, required_evidence,
  material_decisions, authority_boundaries, canonical_refs,
  github_path, github_url, git_commit_sha, git_blob_sha, content_sha256,
  current_wp, lifecycle_state, is_synthetic
) values (
  'BUILD-002',
  'v0.1-draft',
  'build_contract',
  'BUILD-002 — Unified Fusion Hub · Build Contract',
  'Warwick can send information or instructions through the most natural front door — Telegram (DevBot / ShopperBot), forwarded email, voice note, or the Directus cockpit — and one central Fusion hub safely preserves the source, routes it to the correct specialist, records decisions and evidence, and returns a truthful contextual result, without Warwick manually relaying work between systems.',
  'BUILD-002 turns Fusion247''s already-merged capabilities (live capture gateway, TubeAIR, AsdAIr, Tower/Codex QA, Supabase, Directus, the governed Markdown/Obsidian Brain) into one coherent operational hub. Different bots and interfaces are purposeful facades over the same backend. The first complete proof is YouTube knowledge ingress: a URL pasted into Telegram becomes an immutable RAW transcript + a standalone knowledge note in the Brain/vault with justified backlinks, plus learning candidates and a human-readable brief in Directus, and a truthful Telegram completion card — surviving duplicate delivery and restart. This contract is also the lightweight build-acceptance mechanism: versioned in Git (canonical), projected here with its exact path/SHA/hash/approval state, and approved by Warwick via Directus.',
  '["Unified hub contract (one durable event/decision/command spine)","Build-acceptance mechanism (this contract + Supabase record + Directus approval)","YouTube knowledge-ingress walking skeleton (reusing TubeAIR)","Suggested-learnings review loop (Directus Accept/Decline -> governed decision)","Bidirectional control (Telegram A/B/C + one safe Directus command)","Obsidian on the Yoga (localhost-only authenticated API, secret-safe, queue-not-lose)","Bounded Shopper / email / voice adapter routes"]'::jsonb,
  'Autonomous merge; Asda checkout/payment; automatic substitutions; automatic permanent learning without approval; full email client; native app; full Health / CareerAIr; a second Brain or duplicated vault; public/LAN/tailnet Obsidian API exposure; paid Obsidian Sync/Publish; uncontrolled plugins; generic multi-user platform; rebuilding TubeAIR/AsdAIr/Tower/Directus/the merged gateway; replacing the BUILD-014 control plane; retiring ClickUp; backlink spam; low-value entity stubs.',
  '["Establish one coherent Fusion input/decision/command hub","Remove Warwick''s manual relay between channels and workers","Deliver a complete YouTube-to-Brain vertical slice","Make source-derived knowledge readable in Obsidian and Directus","Make learning proposals reviewable, not silently applied","Give Larry durable Telegram and Directus decisions/commands","Establish the lightweight build-contract and approval mechanism","Give Codex merge QA a bounded, approved contract at merge time"]'::jsonb,
  '[{"wp":"WP0","slice":"Build contract -> Supabase draft record -> Directus approval page","gate":"Warwick approval before substantial implementation (THIS session)"},{"wp":"WP1","slice":"Obsidian install + secure localhost API proof","gate":"Secret-safe; outage-queues; reboot recovery"},{"wp":"WP2","slice":"YouTube URL -> RAW -> knowledge note -> Directus -> Telegram","gate":"The walking-skeleton acceptance journey"},{"wp":"WP3","slice":"Suggested-learning Accept/Decline loop","gate":"Durable decision events; governed apply"},{"wp":"WP4","slice":"Directus -> Larry safe command + Telegram A/B/C","gate":"Audited command spine"},{"wp":"WP5","slice":"Shopper integration (AsdAIr route)","gate":"No auto-substitute / no checkout"},{"wp":"WP6","slice":"Bounded email + voice adapter routes","gate":"Metadata-preserving adapter proofs"},{"wp":"WP7","slice":"Restart / duplicate / exact-head Codex merge QA","gate":"READY_TO_MERGE at the exact head"}]'::jsonb,
  '[{"ref":"AC1","text":"Approved build pack: contract in Git; Supabase records exact path/version/SHA/hash; Directus displays it clearly; Warwick can Approve or Request-changes; a material change creates a new version requiring reapproval; approval binds to exact version+SHA+hash."},{"ref":"AC2","text":"Obsidian operational: installed on the Yoga; governed vault opens; existing Markdown/backlinks intact; local API authenticated + localhost-only; worker can read/search/write/open a test note; no secret leaks; outage queues work; recovery via agreed startup path."},{"ref":"AC3","text":"YouTube end-to-end: one durable Telegram event; automatic classify+route; full timestamped transcript; immutable provenance-linked RAW; Karpathy packet; canonical template; standalone knowledge note; Cairn categorisation; justified backlinks; honest claims/uncertainty; truthful Telegram card + links."},{"ref":"AC4","text":"Directus review experience: each source has its own stable readable page (desktop + S21); suggested learnings readable with evidence; Warwick can Accept/Decline each; decisions durable + correlated."},{"ref":"AC5","text":"Bidirectional control: one Telegram A/B/C answer becomes a durable decision reaching Larry/specialist without manual relay; one safe Directus command reaches the hub and returns a receipt."},{"ref":"AC6","text":"Reliability: duplicate URL delivery -> no duplicate artefacts/effects; restart mid-processing reconstructs + completes; exhausted failures do not hammer YouTube; a failed card update never reverses completed work; no false completion."},{"ref":"AC7","text":"Regression: DevBot Save-to-Brain still works; TubeAIR/AsdAIr/Tower/Directus tests+controls green+safe; no private data/secret in the public repo; no canonical note silently overwritten."},{"ref":"AC8","text":"Bounded email + voice proofs: one email/fixture enters the hub with source metadata preserved + routed; one voice input preserved + transcribed; ambiguous voice intent resolves via A/B/C + routes correctly."},{"ref":"AC9","text":"Codex merge QA: Codex receives BUILD ID, approved contract version/hash, exact PR head SHA, scope/non-goals, acceptance criteria, required tests/evidence, actual CI/evidence, Larry claim, exceptions. Missing approval / hash mismatch / moved head / missing evidence fails closed. Codex is QA, does not merge."}]'::jsonb,
  'At completion the PR must carry: approved contract version + content hash; exact branch/PR/head SHA; Directus desktop + S21 proof; Telegram card references; RAW-transcript + processed-note paths; Obsidian API read/search/write/open proof; duplicate + restart proof; CI results (TubeAIR/AsdAIr/gateway/control-plane green); one safe Directus command receipt; A/B/C decision evidence; declared limitations + deferred work.',
  '[{"ref":"D1","text":"One BUILD, several front doors — BUILD-002 is the umbrella; no competing gateway/Brain/store/control-plane; reuse merged components."},{"ref":"D2","text":"WP0 contract record lives in the live cockpit schema, not the DEV-only ops model (which encodes reviewer verification, structurally forbidding Warwick from writing). Warwick contract sign-off is a different concern; uses a minimal cockpit.build_contract projection + a decision/command approval path reusing the live write-back seam. (Larry''s delegated schema decision.)"},{"ref":"D3","text":"''Kaspersky template'' = existing TubeAIR Karpathy packet + canonical F247.template.youtube-transcript-knowledge-note + current immutable-source/classification/backlink rules. No new template invented."},{"ref":"D4","text":"RAW != processed note. RAW is complete, timestamped, immutable evidence; the note is a standalone knowledge reconstruction, never a transcript copy or thin summary."},{"ref":"D5","text":"First-party, non-adversarial threat bar: correctness, accidental-leak safety, availability, audit-integrity — not adversarial hardening."}]'::jsonb,
  'Git/Markdown/Obsidian = canonical durable knowledge; Supabase = operational infra + approved-version/QA record (never the only copy, never a competing Brain); approved domain stores = governed structured records; Directus/Telegram = projections of durable hub state, never authoritative. Directus INSERTS a decision/command request; it does not rewrite approval history — a worker applies the approval bound to the exact version+SHA+hash. Building code + opening one integration PR is authorised; merge to main + any live-sensitive/irreversible/credential/paid action return to Warwick.',
  '[{"label":"Warwick remote-control order — BUILD-002 Unified Hub resumption (2026-07-22)"},{"label":"ClickUp BUILD-002 Doc page 05 (Build Brief)","url":"https://app.clickup.com/90121891946/docs/2kxuxw3a-852/2kxuxw3a-5992"},{"label":"ClickUp BUILD-002 Doc page 06 (Build Contract / PRD)","url":"https://app.clickup.com/90121891946/docs/2kxuxw3a-852/2kxuxw3a-6012"},{"label":"Foundry IDEA-002","url":"https://app.clickup.com/90121891946/docs/2kxuxw3a-732/2kxuxw3a-1132"},{"label":"Foundry IDEA-012 convergence","url":"https://app.clickup.com/90121891946/docs/2kxuxw3a-732/2kxuxw3a-5932"},{"label":"Foundry IDEA-013 convergence","url":"https://app.clickup.com/90121891946/docs/2kxuxw3a-732/2kxuxw3a-5952"}]'::jsonb,
  'Builds/BUILD-002-unified-personal-capture-gateway/BUILD-CONTRACT.md',
  'https://github.com/warwickallan/Fusion247PKA/blob/build-002/unified-fusion-hub/Builds/BUILD-002-unified-personal-capture-gateway/BUILD-CONTRACT.md',
  '96ed15d30c83904d1e615e47e57b54dc5fbe0861',
  '3e6661efd511d0dd2e87c217062b1cdd66540b94',
  '83e1b41a693ea0c7f9a86a79d43db988f937df704f14e82e7a8b4c8203f9cf2c',
  'WP0',
  'draft',
  false
)
on conflict (build_id, contract_version) do update set
  title=excluded.title, outcome=excluded.outcome, executive_summary=excluded.executive_summary,
  scope=excluded.scope, non_goals=excluded.non_goals, objectives=excluded.objectives,
  wp_sequence=excluded.wp_sequence, acceptance_criteria=excluded.acceptance_criteria,
  required_evidence=excluded.required_evidence, material_decisions=excluded.material_decisions,
  authority_boundaries=excluded.authority_boundaries, canonical_refs=excluded.canonical_refs,
  github_url=excluded.github_url, current_wp=excluded.current_wp, updated_at=now();
-- NB: on conflict deliberately does NOT touch lifecycle_state / approved_by / approved_at.
