// =====================================================================
// BUILD-015 AsdAIr - pipeline/finalise/quantityDerivation.js
//
// WO-2026-08-13-10 (WP-B15-40), AC2. THE QUANTITY DERIVATION, EXPOSED.
//
// The 39 lines sum to 53 items. That number was established and is not in
// doubt. What was missing is the DERIVATION - a durable, human-readable chain
//
//     SOURCE LINE -> PRODUCT IDENTITY -> PURCHASE QUANTITY -> FINAL ITEM COUNT
//
// with a test that asserts the sum instead of a person asserting it. If the
// total ever stops matching, the test fails AND NAMES THE LINE, rather than a
// human noticing a different number some weeks later.
//
// ── WARWICK'S RULED CONVENTIONS, APPLIED UPSTREAM, RECORDED HERE ─────────
//   * no explicit quantity on the page  -> 1 retail unit
//   * "xN"                              -> N
//   * PACK SIZE IS IDENTITY, NEVER PURCHASE QUANTITY
//       Richmond 16 -> ONE pack of 16.  Ariel Pods 33 -> ONE pack of 33.
//   * two conflicting readings of ONE physical line -> a HUMAN decides,
//     never a majority guess.
//
// This module DERIVES nothing and DECIDES nothing. Every number it prints was
// computed by `settleQuantity` / `packIdentityRule` and carried through the
// production run; re-deriving them here would produce a second opinion that
// could silently disagree with the shop. It reads the built artefact and shows
// its working.
//
// PURE. No I/O, no model, no clock, no database.
// =====================================================================

'use strict';

/**
 * PURE. One derivation row per final-list line, in the artefact's own order.
 *
 * @param {object} finalList - the `buildFinalList` artefact
 * @returns {Array<object>} rows, each carrying the full chain for one line
 */
export function deriveQuantityRows(finalList) {
  return (finalList.lines || []).map((l) => {
    const d = l.provenance_detail || {};
    return {
      line_no: d.line_no ?? null,
      source_line: d.raw_reading ?? l.list_item_name ?? null,
      product_identity: l.product ?? null,
      product_id: l.product_id ?? null,
      identity_basis: l.product_id !== null && l.product_id !== undefined
        ? (l.match_basis || 'catalogue match')
        : 'UNRESOLVED - no catalogue identity, routed for a human',
      purchase_quantity: Number.isInteger(l.quantity) ? l.quantity : null,
      quantity_basis: l.quantity_basis ?? null,
      quantity_settled: l.quantity_settled === true,
      quantity_candidates: Array.isArray(l.quantity_candidates) ? l.quantity_candidates : [],
      pack_identity_applied: l.pack_identity_applied === true,
      pack_identity_refused_evidence: l.pack_identity_refused_evidence ?? null,
      note: l.quantity_note ?? null,
      shoppable: l.shoppable === true,
      held_reason: l.held_reason ?? null,
      human_route_causes: Array.isArray(d.human_route_causes) ? d.human_route_causes : [],
    };
  });
}

/**
 * PURE. The arithmetic, computed from the rows so the artefact cannot disagree
 * with itself, alongside the totals the final list independently declares.
 *
 * `reconciles` is the whole point: it is the machine-checkable claim that the
 * derivation and the shop agree about how many items are being bought.
 */
export function summariseQuantities(finalList) {
  const rows = deriveQuantityRows(finalList);
  const additions = finalList.additions || [];

  const lineItems = rows.reduce((n, r) => n + (Number.isInteger(r.purchase_quantity) ? r.purchase_quantity : 0), 0);
  const additionItems = additions.reduce((n, a) => n + (Number.isInteger(a.quantity) ? a.quantity : 0), 0);
  const declared = finalList.totals ? finalList.totals.item_count : null;

  return {
    rows,
    line_count: rows.length,
    lines_with_no_quantity: rows.filter((r) => r.purchase_quantity === null).map((r) => r.line_no),
    derived_line_items: lineItems,
    derived_addition_items: additionItems,
    derived_item_count: lineItems + additionItems,
    declared_item_count: declared,
    reconciles: lineItems + additionItems === declared,
    pack_identity_lines: rows.filter((r) => r.pack_identity_applied).map((r) => r.line_no),
    unsettled_lines: rows.filter((r) => !r.quantity_settled).map((r) => r.line_no),
  };
}

/** A human-readable rendering of the same derivation. Derived, never authored. */
export function renderQuantityDerivationMarkdown(finalList) {
  const s = summariseQuantities(finalList);
  const out = [];

  out.push(`# AsdAIr quantity derivation - ${finalList.shop_ref}`);
  out.push('');
  out.push('> WO-2026-08-13-10 (WP-B15-40) AC2. GENERATED by `finalise/quantityDerivation.js`');
  out.push('> from the built artefact. Do not hand-edit: every number here was computed by');
  out.push('> `settleQuantity` during the production run, and `quantityDerivation.test.js`');
  out.push('> fails and names the line if this stops summing.');
  out.push('');
  out.push(`> ${finalList.not_a_live_run}`);
  out.push('');
  out.push('## The arithmetic');
  out.push('');
  out.push(`- Lines: **${s.line_count}**`);
  out.push(`- Items from those lines: **${s.derived_line_items}**`);
  out.push(`- Items from separately justified additions: **${s.derived_addition_items}**`);
  out.push(`- **Derived item count: ${s.derived_item_count}**`);
  out.push(`- Declared by the final list: **${s.declared_item_count}**`);
  out.push(`- Reconciles: **${s.reconciles ? 'YES' : 'NO'}**`);
  out.push('');
  out.push('## Warwick\'s ruled conventions');
  out.push('');
  out.push('| Convention | Effect on PURCHASE QUANTITY |');
  out.push('|---|---|');
  out.push('| No explicit quantity written on the page | 1 retail unit |');
  out.push('| `xN` written on the page | N |');
  out.push('| A pack size (Richmond 16, Ariel Pods 33) | **1** - pack size is IDENTITY, never purchase quantity |');
  out.push('| Two readings of one physical line conflict | **HUMAN decides** - never a majority guess |');
  out.push('');
  out.push('## SOURCE LINE -> PRODUCT IDENTITY -> PURCHASE QUANTITY');
  out.push('');
  out.push('| # | Source line (as written on the page) | Product identity | Qty | Basis | Pack rule | Ready | Note |');
  out.push('|---:|---|---|---:|---|---|---|---|');
  for (const r of s.rows) {
    const clean = (v) => String(v ?? '').replace(/\|/g, '/').replace(/\r?\n/g, ' ');
    const ready = r.shoppable ? 'yes' : `HUMAN (${clean(r.held_reason || r.human_route_causes.join(', ') || 'held')})`;
    out.push(`| ${r.line_no ?? '-'} | \`${clean(r.source_line)}\` | ${clean(r.product_identity) || `_unresolved_`} | ${r.purchase_quantity ?? '-'} | ${clean(r.quantity_basis) || '-'} | ${r.pack_identity_applied ? 'applied' : '-'} | ${ready} | ${clean(r.note)} |`);
  }
  out.push('');
  out.push(`**TOTAL PURCHASE QUANTITY ACROSS ALL LINES: ${s.derived_line_items}**`);
  if (s.derived_addition_items > 0) {
    out.push('');
    out.push(`Plus ${s.derived_addition_items} item(s) from separately justified additions (NOT photo lines).`);
  }
  out.push('');
  out.push(`**FINAL ITEM COUNT: ${s.derived_item_count}** (declared: ${s.declared_item_count}; reconciles: ${s.reconciles ? 'YES' : 'NO'})`);
  out.push('');
  return `${out.join('\n')}\n`;
}
