-- =============================================================================
-- MyPKA cockpit migration 050 — portfolio/build-state RECORDS (own schema)
--
-- Per Warwick's architecture decision: portfolio/build-state records land in their OWN schema in
-- MyPKA. These are the SAME underlying records that drive BOTH the Desktop and Mobile native
-- Directus dashboards — only presentation differs. Warwick-editable (plain PM language; no Git).
--
-- Idempotent. Reversible: drop schema cockpit cascade;
-- =============================================================================
create schema if not exists cockpit;

-- Active builds — outcome-led, plain English. progress_pct = acceptance outcomes, not files.
create table if not exists cockpit.build (
  id            bigint generated by default as identity primary key,
  name          text not null,
  gives         text not null,                 -- the intended OUTCOME, in Warwick's words
  domain        text,                           -- grouping for the desktop domain summaries
  status        text not null,                  -- plain-English status label
  status_tone   text not null default 'ok'      -- ok | warn | prog | park | block  (drives the chip colour)
                  check (status_tone in ('ok','warn','prog','park','block')),
  progress_pct  int  not null default 0 check (progress_pct between 0 and 100),
  current_step  text,
  next_result   text,                           -- next VISIBLE result
  sort          int  not null default 0,
  updated_at    timestamptz not null default now()
);

-- Decisions waiting for Warwick (the "needs your attention" list; keep it short).
create table if not exists cockpit.decision (
  id            bigint generated by default as identity primary key,
  priority      int  not null default 1,
  title         text not null,                  -- what happened / what it is
  why           text,                            -- why it matters
  recommendation text,                           -- Larry's recommendation
  cost          text,                            -- consequence of doing nothing
  resolved      boolean not null default false,
  sort          int not null default 0,
  updated_at    timestamptz not null default now()
);

-- Recent movement — human-meaningful outcomes only (no commit SHAs / branches / CI).
create table if not exists cockpit.movement (
  id           bigint generated by default as identity primary key,
  happened_at  timestamptz not null default now(),
  text         text not null,
  tone         text not null default 'ok' check (tone in ('ok','warn','block'))
);

-- Domain summaries (desktop) — one line per domain of the operation.
create table if not exists cockpit.domain_summary (
  id       bigint generated by default as identity primary key,
  domain   text not null,
  headline text not null,
  tone     text not null default 'ok' check (tone in ('ok','warn','block','park')),
  sort     int not null default 0
);

-- Overall state (single logical row) — the five-second read.
create table if not exists cockpit.overall_state (
  id        int primary key default 1 check (id = 1),
  word      text not null,                       -- On track | Attention needed | Blocked
  headline  text not null,
  sub       text not null,
  tone      text not null default 'ok' check (tone in ('ok','warn','block')),
  larry_now text,                                 -- what Larry is doing right now
  updated_at timestamptz not null default now()
);
