-- BUILD-014 Tower supervisor loop — minimal durable turn schema (SQLite, WAL).
-- WO-TW-01: translated from the Postgres original. Semantics preserved at CURRENT scope; no
-- model change. Codex acts as GPT-style product supervisor; the FULL exchange is stored here
-- durably so a turn can be reconstructed after a restart. DEV/synthetic. No AsdAIr/live data.
-- Idempotent: every statement is `if not exists`, safe to run repeatedly (watcher.mjs re-applies
-- all four files on boot).
--
-- ── THE FOUR DIALECT FACTS, stated once here and not repeated per file ────────────────────────
--
-- 1) SCHEMA. Postgres had `create schema tower`. SQLite has ATTACH: db.mjs attaches the store
--    file under the alias `tower`, so every DML literal still reads `tower.turn`. In DDL the
--    qualifier goes on the INDEX name and the table is bare — `create index tower.x on turn(...)`.
--
-- 2) COLUMNS THAT ARRIVED BY DELTA ARE DECLARED ON THE TABLE THAT OWNS THEM. SQLite has neither
--    `alter table ... add column if not exists` nor `alter table ... add constraint`, so a
--    forward-only chain of ALTERs cannot be replayed idempotently the way the Postgres files
--    were. Each column and table-level constraint is therefore declared inline on the CREATE
--    TABLE of the table that owns it, with the delta it came from named beside it. THE POST-APPLY
--    SHAPE IS IDENTICAL; only the file a column is written in moved. The other three files keep
--    their own tables, indexes and constraints, so `applyWatcherSchema` / `applyHoldSchema` /
--    `applyCommentSchema` all still do real work.
--
-- 3) TYPES. `uuid` → text (a v4 string generated by the column default); `timestamptz` → ISO-8601
--    text, byte-identical to Date#toISOString, rehydrated to Date by db.mjs; `boolean` → 0/1,
--    coerced back to real booleans by db.mjs; `jsonb` → text, parsed by db.mjs. The coercion is
--    per column NAME and lives in db.mjs — read it before adding a column of a new type.
--
-- 4) `bigint generated always as identity` → `integer primary key autoincrement`. SQLite can only
--    auto-assign an INTEGER PRIMARY KEY, and a value assigned by a trigger would arrive AFTER the
--    RETURNING clause is evaluated (so `insert ... returning seq` would hand back null). `seq` is
--    therefore the rowid alias and `id` carries `not null unique`, which in SQLite is the same
--    index and the same guarantee a TEXT primary key would have given. Nothing reads the primary
--    key as such; `order by seq` and `id` lookups both behave exactly as before.

-- The active Warwick-approved GPT product-supervisor prompt. Loaded FIRST on every turn.
create table if not exists tower.supervisor_prompt (
  id           text primary key default (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab',abs(random())%4+1,1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
  version      integer not null,
  content      text    not null,
  content_hash text    not null,          -- sha256 of content, bound onto every review
  active       integer not null default 0,
  approved_by  text,
  created_at   text    not null default (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
-- At most one active prompt.
create unique index if not exists tower.supervisor_prompt_single_active
  on supervisor_prompt (active) where active;

-- One governed turn: the Warwick/Tower instruction + Larry's response, bound to the prompt used.
create table if not exists tower.turn (
  seq            integer primary key autoincrement,   -- was: bigint generated always as identity
  id             text not null unique default (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab',abs(random())%4+1,1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
  build_ref      text not null default 'BUILD-014',
  prompt_id      text references supervisor_prompt(id),
  prompt_version integer,
  prompt_hash    text,
  instruction    text not null,           -- what Warwick / Tower asked
  larry_response text,                    -- Larry's response or proposed action
  state          text not null default 'open',  -- open|pending|claimed|held|reviewed|acted|blocked|awaiting_warwick|complete
  created_at     text not null default (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  updated_at     text not null default (strftime('%Y-%m-%dT%H:%M:%fZ','now')),

  -- from db/watcher_schema.sql §1 — the durable lease, the ONLY way the watcher can guarantee an
  -- exactly-once claim across restarts. `state` is free text (no CHECK), so 'pending'/'claimed'
  -- need no enum change.
  lease_owner       text,
  lease_deadline_at text,

  -- from db/watcher_schema.sql §2 — a durable goal-complete signal carried on the turn, because
  -- the watcher processes turns purely from the DB and a caller's flag must live on the row.
  goal_complete integer not null default 0,

  -- from db/watcher_schema.sql §7 — merge-class turn fields (FIX 1). All nullable; ordinary turns
  -- leave them unset. NOTE head_sha is deliberately PLAIN TEXT and is NOT bound by
  -- git_sha_canonical_chk: the CI suite seeds non-canonical heads on purpose ('aaaa1111bbbb2222'
  -- in T5, 'UNRESOLVABLE' in T6) to exercise the fail-closed evidence path. See the scope note in
  -- db/comment_schema.sql — the guarantee is one-sided by ruling, and DO NOT WIDEN it here.
  kind      text not null default 'ordinary',
  pr_number integer,
  repo      text,
  base_sha  text,
  head_sha  text,

  -- from db/watcher_schema.sql §8 — idempotent ingest key (FIX 2). Nullable + UNIQUE via a
  -- partial index below: turns created without a key (e.g. the accept harness) stay unconstrained.
  session_turn_key text,

  -- from db/hold_schema.sql — the DURABLE HOLD model. A turn in state='held' is OUT of the normal
  -- loop entirely: claimOne (state='pending') and reclaimStale (state='claimed') both ignore it,
  -- so it is never claimed, reviewed or notified, and NO lease expiry can silently release it.
  held_at     text,
  held_by     text,
  hold_reason text,
  hold_until  text
);

-- Codex's supervisor review of a reconstructed turn (Codex never sees the store; Tower stages).
create table if not exists tower.supervisor_review (
  id            text primary key default (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab',abs(random())%4+1,1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
  turn_id       text not null references turn(id),
  reviewer      text not null default 'gpt_codex',
  model_id      text,
  packet_hash   text,                      -- hash of the reconstructed turn staged to Codex
  aligned          integer,                -- is Larry doing what Warwick asked?
  over_engineering integer,
  drifting         integer,                -- into governance/architecture/scope
  administering    integer,                -- merely administering vs delivering
  next_action   text,
  warwick_needed integer,
  verdict       text,                      -- continue|correct|block|ask_warwick
  summary       text,
  raw_output    text,                      -- jsonb
  created_at    text not null default (strftime('%Y-%m-%dT%H:%M:%fZ','now')),

  -- from db/watcher_schema.sql §3 — the exact text staged to Codex (base reconstructed turn +
  -- injected open findings), persisted verbatim so the audit claim is byte-checkable after a
  -- restart. packet_hash = sha256(staged_input).
  staged_input text,

  -- from db/watcher_schema.sql §9 — which supervisor prompt(s) ran + their fingerprints, and the
  -- merge-class QA review result. Ordinary turns carry only the delivery supervisor.
  prompts_applied text,                    -- jsonb
  merge_review    text                     -- jsonb
);

-- Every automatic Telegram the Watcher sends (real delivery result recorded).
create table if not exists tower.notification (
  id                  text primary key default (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab',abs(random())%4+1,1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
  turn_id             text references turn(id),
  reason              text not null,       -- warwick_input_required|codex_block_or_redirect|goal_complete|tower_failure
  state               text not null,
  message             text not null,
  telegram_ok         integer,
  telegram_message_id integer,
  created_at          text not null default (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
